/* tslint:disable */
/* eslint-disable */
/**
 * Hyper Fleet Native API
 * Hyper Fleet Native API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CommandKillResponse,
  CommandListResponse,
  CommandRunResponse,
  CommandWaitResponse,
  CreatePTYSession200Response,
  CreatePTYSessionRequest,
  ErrorResponse,
  ExecRequest,
  ExecResponse,
  ExecuteInSessionRequest,
  GetPTYBuffer200Response,
  KillBackgroundProcessRequest,
  ListPTYSessions200Response,
  ResizeTerminalRequest,
  RunBackgroundCommandRequest,
  SuccessResponse,
} from '../models/index';
import {
    CommandKillResponseFromJSON,
    CommandKillResponseToJSON,
    CommandListResponseFromJSON,
    CommandListResponseToJSON,
    CommandRunResponseFromJSON,
    CommandRunResponseToJSON,
    CommandWaitResponseFromJSON,
    CommandWaitResponseToJSON,
    CreatePTYSession200ResponseFromJSON,
    CreatePTYSession200ResponseToJSON,
    CreatePTYSessionRequestFromJSON,
    CreatePTYSessionRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ExecRequestFromJSON,
    ExecRequestToJSON,
    ExecResponseFromJSON,
    ExecResponseToJSON,
    ExecuteInSessionRequestFromJSON,
    ExecuteInSessionRequestToJSON,
    GetPTYBuffer200ResponseFromJSON,
    GetPTYBuffer200ResponseToJSON,
    KillBackgroundProcessRequestFromJSON,
    KillBackgroundProcessRequestToJSON,
    ListPTYSessions200ResponseFromJSON,
    ListPTYSessions200ResponseToJSON,
    ResizeTerminalRequestFromJSON,
    ResizeTerminalRequestToJSON,
    RunBackgroundCommandRequestFromJSON,
    RunBackgroundCommandRequestToJSON,
    SuccessResponseFromJSON,
    SuccessResponseToJSON,
} from '../models/index';

export interface AttachToBackgroundProcessRequest {
    id: string;
    killBackgroundProcessRequest: KillBackgroundProcessRequest;
}

export interface ConnectPTYRequest {
    id: string;
}

export interface ConnectPTYSessionRequest {
    id: string;
    sessionId: string;
}

export interface CreatePTYSessionOperationRequest {
    id: string;
    createPTYSessionRequest?: CreatePTYSessionRequest;
}

export interface DeletePTYSessionRequest {
    id: string;
    sessionId: string;
}

export interface ExecCommandRequest {
    id: string;
    execRequest: ExecRequest;
}

export interface ExecCommandStreamRequest {
    id: string;
    execRequest: ExecRequest;
}

export interface ExecuteInPTYSessionRequest {
    id: string;
    sessionId: string;
    executeInSessionRequest: ExecuteInSessionRequest;
}

export interface GetPTYBufferRequest {
    id: string;
    sessionId: string;
}

export interface KillBackgroundProcessOperationRequest {
    id: string;
    killBackgroundProcessRequest: KillBackgroundProcessRequest;
}

export interface ListBackgroundProcessesRequest {
    id: string;
}

export interface ListPTYSessionsRequest {
    id: string;
}

export interface ResizeTerminalOperationRequest {
    id: string;
    sessionId: string;
    resizeTerminalRequest: ResizeTerminalRequest;
}

export interface RunBackgroundCommandOperationRequest {
    id: string;
    runBackgroundCommandRequest: RunBackgroundCommandRequest;
}

export interface WaitForBackgroundProcessRequest {
    id: string;
    killBackgroundProcessRequest: KillBackgroundProcessRequest;
}

/**
 * 
 */
export class ExecutionApi extends runtime.BaseAPI {

    /**
     * Connect to a background process and stream its output as Server-Sent Events. Events: `stdout`, `stderr`, `exit`, `error`. 
     * Attach to process output (SSE stream)
     */
    async attachToBackgroundProcessRaw(requestParameters: AttachToBackgroundProcessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling attachToBackgroundProcess().'
            );
        }

        if (requestParameters['killBackgroundProcessRequest'] == null) {
            throw new runtime.RequiredError(
                'killBackgroundProcessRequest',
                'Required parameter "killBackgroundProcessRequest" was null or undefined when calling attachToBackgroundProcess().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/{id}/commands/attach`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: KillBackgroundProcessRequestToJSON(requestParameters['killBackgroundProcessRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Connect to a background process and stream its output as Server-Sent Events. Events: `stdout`, `stderr`, `exit`, `error`. 
     * Attach to process output (SSE stream)
     */
    async attachToBackgroundProcess(requestParameters: AttachToBackgroundProcessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.attachToBackgroundProcessRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Establish a WebSocket connection for temporary terminal access. The WebSocket URL format is: `ws://host/api/sandboxes/{id}/pty` 
     * Connect to ephemeral PTY (WebSocket)
     */
    async connectPTYRaw(requestParameters: ConnectPTYRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling connectPTY().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/{id}/pty`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Establish a WebSocket connection for temporary terminal access. The WebSocket URL format is: `ws://host/api/sandboxes/{id}/pty` 
     * Connect to ephemeral PTY (WebSocket)
     */
    async connectPTY(requestParameters: ConnectPTYRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.connectPTYRaw(requestParameters, initOverrides);
    }

    /**
     * Establish a WebSocket connection to a PTY session for interactive terminal access. The WebSocket URL format is: `ws://host/api/sandboxes/{id}/pty/sessions/{sessionId}` 
     * Connect to PTY session (WebSocket)
     */
    async connectPTYSessionRaw(requestParameters: ConnectPTYSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling connectPTYSession().'
            );
        }

        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling connectPTYSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/{id}/pty/sessions/{sessionId}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"sessionId"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Establish a WebSocket connection to a PTY session for interactive terminal access. The WebSocket URL format is: `ws://host/api/sandboxes/{id}/pty/sessions/{sessionId}` 
     * Connect to PTY session (WebSocket)
     */
    async connectPTYSession(requestParameters: ConnectPTYSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.connectPTYSessionRaw(requestParameters, initOverrides);
    }

    /**
     * Create a new PTY (pseudo-terminal) session for interactive commands
     * Create PTY session
     */
    async createPTYSessionRaw(requestParameters: CreatePTYSessionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreatePTYSession200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createPTYSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/{id}/pty/sessions`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePTYSessionRequestToJSON(requestParameters['createPTYSessionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreatePTYSession200ResponseFromJSON(jsonValue));
    }

    /**
     * Create a new PTY (pseudo-terminal) session for interactive commands
     * Create PTY session
     */
    async createPTYSession(requestParameters: CreatePTYSessionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreatePTYSession200Response> {
        const response = await this.createPTYSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Close and delete a PTY session
     * Delete PTY session
     */
    async deletePTYSessionRaw(requestParameters: DeletePTYSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deletePTYSession().'
            );
        }

        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling deletePTYSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/{id}/pty/sessions/{sessionId}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"sessionId"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessResponseFromJSON(jsonValue));
    }

    /**
     * Close and delete a PTY session
     * Delete PTY session
     */
    async deletePTYSession(requestParameters: DeletePTYSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessResponse> {
        const response = await this.deletePTYSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Execute a command in the sandbox and wait for the result
     * Execute command (synchronous)
     */
    async execCommandRaw(requestParameters: ExecCommandRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExecResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling execCommand().'
            );
        }

        if (requestParameters['execRequest'] == null) {
            throw new runtime.RequiredError(
                'execRequest',
                'Required parameter "execRequest" was null or undefined when calling execCommand().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/{id}/exec`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ExecRequestToJSON(requestParameters['execRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExecResponseFromJSON(jsonValue));
    }

    /**
     * Execute a command in the sandbox and wait for the result
     * Execute command (synchronous)
     */
    async execCommand(requestParameters: ExecCommandRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExecResponse> {
        const response = await this.execCommandRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Execute a command and stream output as Server-Sent Events. Events: `stdout`, `stderr`, and final `exit`. 
     * Execute command (SSE stream)
     */
    async execCommandStreamRaw(requestParameters: ExecCommandStreamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling execCommandStream().'
            );
        }

        if (requestParameters['execRequest'] == null) {
            throw new runtime.RequiredError(
                'execRequest',
                'Required parameter "execRequest" was null or undefined when calling execCommandStream().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/{id}/exec-stream`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ExecRequestToJSON(requestParameters['execRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Execute a command and stream output as Server-Sent Events. Events: `stdout`, `stderr`, and final `exit`. 
     * Execute command (SSE stream)
     */
    async execCommandStream(requestParameters: ExecCommandStreamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.execCommandStreamRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Execute a command asynchronously in an existing PTY session
     * Execute command in PTY session
     */
    async executeInPTYSessionRaw(requestParameters: ExecuteInPTYSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling executeInPTYSession().'
            );
        }

        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling executeInPTYSession().'
            );
        }

        if (requestParameters['executeInSessionRequest'] == null) {
            throw new runtime.RequiredError(
                'executeInSessionRequest',
                'Required parameter "executeInSessionRequest" was null or undefined when calling executeInPTYSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/{id}/pty/sessions/{sessionId}/execute`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"sessionId"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ExecuteInSessionRequestToJSON(requestParameters['executeInSessionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessResponseFromJSON(jsonValue));
    }

    /**
     * Execute a command asynchronously in an existing PTY session
     * Execute command in PTY session
     */
    async executeInPTYSession(requestParameters: ExecuteInPTYSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessResponse> {
        const response = await this.executeInPTYSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the current output buffer from a PTY session
     * Get output buffer
     */
    async getPTYBufferRaw(requestParameters: GetPTYBufferRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetPTYBuffer200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getPTYBuffer().'
            );
        }

        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling getPTYBuffer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/{id}/pty/sessions/{sessionId}/buffer`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"sessionId"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetPTYBuffer200ResponseFromJSON(jsonValue));
    }

    /**
     * Get the current output buffer from a PTY session
     * Get output buffer
     */
    async getPTYBuffer(requestParameters: GetPTYBufferRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetPTYBuffer200Response> {
        const response = await this.getPTYBufferRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Terminate a running background process by PID
     * Kill background process
     */
    async killBackgroundProcessRaw(requestParameters: KillBackgroundProcessOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommandKillResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling killBackgroundProcess().'
            );
        }

        if (requestParameters['killBackgroundProcessRequest'] == null) {
            throw new runtime.RequiredError(
                'killBackgroundProcessRequest',
                'Required parameter "killBackgroundProcessRequest" was null or undefined when calling killBackgroundProcess().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/{id}/commands/kill`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: KillBackgroundProcessRequestToJSON(requestParameters['killBackgroundProcessRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommandKillResponseFromJSON(jsonValue));
    }

    /**
     * Terminate a running background process by PID
     * Kill background process
     */
    async killBackgroundProcess(requestParameters: KillBackgroundProcessOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommandKillResponse> {
        const response = await this.killBackgroundProcessRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get list of all running background processes in the sandbox
     * List running processes
     */
    async listBackgroundProcessesRaw(requestParameters: ListBackgroundProcessesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommandListResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listBackgroundProcesses().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/{id}/commands/list`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommandListResponseFromJSON(jsonValue));
    }

    /**
     * Get list of all running background processes in the sandbox
     * List running processes
     */
    async listBackgroundProcesses(requestParameters: ListBackgroundProcessesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommandListResponse> {
        const response = await this.listBackgroundProcessesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all active PTY sessions for a sandbox
     * List PTY sessions
     */
    async listPTYSessionsRaw(requestParameters: ListPTYSessionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListPTYSessions200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listPTYSessions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/{id}/pty/sessions`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListPTYSessions200ResponseFromJSON(jsonValue));
    }

    /**
     * Get all active PTY sessions for a sandbox
     * List PTY sessions
     */
    async listPTYSessions(requestParameters: ListPTYSessionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListPTYSessions200Response> {
        const response = await this.listPTYSessionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Resize the terminal dimensions for a PTY session
     * Resize terminal
     */
    async resizeTerminalRaw(requestParameters: ResizeTerminalOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling resizeTerminal().'
            );
        }

        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling resizeTerminal().'
            );
        }

        if (requestParameters['resizeTerminalRequest'] == null) {
            throw new runtime.RequiredError(
                'resizeTerminalRequest',
                'Required parameter "resizeTerminalRequest" was null or undefined when calling resizeTerminal().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/{id}/pty/sessions/{sessionId}/resize`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"sessionId"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ResizeTerminalRequestToJSON(requestParameters['resizeTerminalRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessResponseFromJSON(jsonValue));
    }

    /**
     * Resize the terminal dimensions for a PTY session
     * Resize terminal
     */
    async resizeTerminal(requestParameters: ResizeTerminalOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessResponse> {
        const response = await this.resizeTerminalRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Start a command as a background process and return its PID
     * Start background process
     */
    async runBackgroundCommandRaw(requestParameters: RunBackgroundCommandOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommandRunResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling runBackgroundCommand().'
            );
        }

        if (requestParameters['runBackgroundCommandRequest'] == null) {
            throw new runtime.RequiredError(
                'runBackgroundCommandRequest',
                'Required parameter "runBackgroundCommandRequest" was null or undefined when calling runBackgroundCommand().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/{id}/commands/run`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RunBackgroundCommandRequestToJSON(requestParameters['runBackgroundCommandRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommandRunResponseFromJSON(jsonValue));
    }

    /**
     * Start a command as a background process and return its PID
     * Start background process
     */
    async runBackgroundCommand(requestParameters: RunBackgroundCommandOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommandRunResponse> {
        const response = await this.runBackgroundCommandRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Block until a background process completes and return its exit code
     * Wait for process completion
     */
    async waitForBackgroundProcessRaw(requestParameters: WaitForBackgroundProcessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommandWaitResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling waitForBackgroundProcess().'
            );
        }

        if (requestParameters['killBackgroundProcessRequest'] == null) {
            throw new runtime.RequiredError(
                'killBackgroundProcessRequest',
                'Required parameter "killBackgroundProcessRequest" was null or undefined when calling waitForBackgroundProcess().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/{id}/commands/wait`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: KillBackgroundProcessRequestToJSON(requestParameters['killBackgroundProcessRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommandWaitResponseFromJSON(jsonValue));
    }

    /**
     * Block until a background process completes and return its exit code
     * Wait for process completion
     */
    async waitForBackgroundProcess(requestParameters: WaitForBackgroundProcessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommandWaitResponse> {
        const response = await this.waitForBackgroundProcessRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
