/* tslint:disable */
/* eslint-disable */
/**
 * VoidRun API
 * VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/version` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CommandKillResponse,
    CommandKillResponseFromJSON,
    CommandKillResponseToJSON,
} from '../models/CommandKillResponse';
import {
    type CommandListResponse,
    CommandListResponseFromJSON,
    CommandListResponseToJSON,
} from '../models/CommandListResponse';
import {
    type CommandRunResponse,
    CommandRunResponseFromJSON,
    CommandRunResponseToJSON,
} from '../models/CommandRunResponse';
import {
    type CommandWaitResponse,
    CommandWaitResponseFromJSON,
    CommandWaitResponseToJSON,
} from '../models/CommandWaitResponse';
import {
    type CreatePTYSession200Response,
    CreatePTYSession200ResponseFromJSON,
    CreatePTYSession200ResponseToJSON,
} from '../models/CreatePTYSession200Response';
import {
    type CreatePTYSessionRequest,
    CreatePTYSessionRequestFromJSON,
    CreatePTYSessionRequestToJSON,
} from '../models/CreatePTYSessionRequest';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse';
import {
    type ExecRequest,
    ExecRequestFromJSON,
    ExecRequestToJSON,
} from '../models/ExecRequest';
import {
    type ExecResponse,
    ExecResponseFromJSON,
    ExecResponseToJSON,
} from '../models/ExecResponse';
import {
    type ExecuteInSessionRequest,
    ExecuteInSessionRequestFromJSON,
    ExecuteInSessionRequestToJSON,
} from '../models/ExecuteInSessionRequest';
import {
    type GetPTYBuffer200Response,
    GetPTYBuffer200ResponseFromJSON,
    GetPTYBuffer200ResponseToJSON,
} from '../models/GetPTYBuffer200Response';
import {
    type KillBackgroundProcessRequest,
    KillBackgroundProcessRequestFromJSON,
    KillBackgroundProcessRequestToJSON,
} from '../models/KillBackgroundProcessRequest';
import {
    type ListPTYSessions200Response,
    ListPTYSessions200ResponseFromJSON,
    ListPTYSessions200ResponseToJSON,
} from '../models/ListPTYSessions200Response';
import {
    type ResizeTerminalRequest,
    ResizeTerminalRequestFromJSON,
    ResizeTerminalRequestToJSON,
} from '../models/ResizeTerminalRequest';
import {
    type RunBackgroundCommandRequest,
    RunBackgroundCommandRequestFromJSON,
    RunBackgroundCommandRequestToJSON,
} from '../models/RunBackgroundCommandRequest';
import {
    type SessionExecRequest,
    SessionExecRequestFromJSON,
    SessionExecRequestToJSON,
} from '../models/SessionExecRequest';
import {
    type SessionExecResponse,
    SessionExecResponseFromJSON,
    SessionExecResponseToJSON,
} from '../models/SessionExecResponse';
import {
    type SessionExecStreamRequest,
    SessionExecStreamRequestFromJSON,
    SessionExecStreamRequestToJSON,
} from '../models/SessionExecStreamRequest';
import {
    type SuccessResponse,
    SuccessResponseFromJSON,
    SuccessResponseToJSON,
} from '../models/SuccessResponse';

export interface AttachToBackgroundProcessRequest {
    id: string;
    killBackgroundProcessRequest: KillBackgroundProcessRequest;
}

export interface ConnectPTYRequest {
    id: string;
}

export interface ConnectPTYSessionRequest {
    id: string;
    sessionId: string;
}

export interface CreatePTYSessionOperationRequest {
    id: string;
    createPTYSessionRequest?: CreatePTYSessionRequest;
}

export interface DeletePTYSessionRequest {
    id: string;
    sessionId: string;
}

export interface ExecCommandRequest {
    id: string;
    execRequest: ExecRequest;
}

export interface ExecCommandStreamRequest {
    id: string;
    execRequest: ExecRequest;
}

export interface ExecuteInPTYSessionRequest {
    id: string;
    sessionId: string;
    executeInSessionRequest: ExecuteInSessionRequest;
}

export interface GetPTYBufferRequest {
    id: string;
    sessionId: string;
}

export interface KillBackgroundProcessOperationRequest {
    id: string;
    killBackgroundProcessRequest: KillBackgroundProcessRequest;
}

export interface ListBackgroundProcessesRequest {
    id: string;
}

export interface ListPTYSessionsRequest {
    id: string;
}

export interface ResizeTerminalOperationRequest {
    id: string;
    sessionId: string;
    resizeTerminalRequest: ResizeTerminalRequest;
}

export interface RunBackgroundCommandOperationRequest {
    id: string;
    runBackgroundCommandRequest: RunBackgroundCommandRequest;
}

export interface SessionExecOperationRequest {
    id: string;
    sessionExecRequest: SessionExecRequest;
}

export interface SessionExecStreamOperationRequest {
    id: string;
    sessionExecStreamRequest: SessionExecStreamRequest;
}

export interface WaitForBackgroundProcessRequest {
    id: string;
    killBackgroundProcessRequest: KillBackgroundProcessRequest;
}

/**
 * 
 */
export class ExecutionApi extends runtime.BaseAPI {

    /**
     * Creates request options for attachToBackgroundProcess without sending the request
     */
    async attachToBackgroundProcessRequestOpts(requestParameters: AttachToBackgroundProcessRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling attachToBackgroundProcess().'
            );
        }

        if (requestParameters['killBackgroundProcessRequest'] == null) {
            throw new runtime.RequiredError(
                'killBackgroundProcessRequest',
                'Required parameter "killBackgroundProcessRequest" was null or undefined when calling attachToBackgroundProcess().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/{id}/commands/attach`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: KillBackgroundProcessRequestToJSON(requestParameters['killBackgroundProcessRequest']),
        };
    }

    /**
     * Connect to a background process and stream its output as Server-Sent Events. Events: `stdout`, `stderr`, `exit`, `error`. 
     * Attach to process output (SSE stream)
     */
    async attachToBackgroundProcessRaw(requestParameters: AttachToBackgroundProcessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.attachToBackgroundProcessRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Connect to a background process and stream its output as Server-Sent Events. Events: `stdout`, `stderr`, `exit`, `error`. 
     * Attach to process output (SSE stream)
     */
    async attachToBackgroundProcess(requestParameters: AttachToBackgroundProcessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.attachToBackgroundProcessRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for connectPTY without sending the request
     */
    async connectPTYRequestOpts(requestParameters: ConnectPTYRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling connectPTY().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/{id}/pty`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Establish a WebSocket connection for temporary terminal access. The WebSocket URL format is: `ws://host/api/sandboxes/{id}/pty` 
     * Connect to ephemeral PTY (WebSocket)
     */
    async connectPTYRaw(requestParameters: ConnectPTYRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.connectPTYRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Establish a WebSocket connection for temporary terminal access. The WebSocket URL format is: `ws://host/api/sandboxes/{id}/pty` 
     * Connect to ephemeral PTY (WebSocket)
     */
    async connectPTY(requestParameters: ConnectPTYRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.connectPTYRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for connectPTYSession without sending the request
     */
    async connectPTYSessionRequestOpts(requestParameters: ConnectPTYSessionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling connectPTYSession().'
            );
        }

        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling connectPTYSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/{id}/pty/sessions/{sessionId}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace('{sessionId}', encodeURIComponent(String(requestParameters['sessionId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Establish a WebSocket connection to a PTY session for interactive terminal access. The WebSocket URL format is: `ws://host/api/sandboxes/{id}/pty/sessions/{sessionId}` 
     * Connect to PTY session (WebSocket)
     */
    async connectPTYSessionRaw(requestParameters: ConnectPTYSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.connectPTYSessionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Establish a WebSocket connection to a PTY session for interactive terminal access. The WebSocket URL format is: `ws://host/api/sandboxes/{id}/pty/sessions/{sessionId}` 
     * Connect to PTY session (WebSocket)
     */
    async connectPTYSession(requestParameters: ConnectPTYSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.connectPTYSessionRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for createPTYSession without sending the request
     */
    async createPTYSessionRequestOpts(requestParameters: CreatePTYSessionOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createPTYSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/{id}/pty/sessions`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePTYSessionRequestToJSON(requestParameters['createPTYSessionRequest']),
        };
    }

    /**
     * Create a new PTY (pseudo-terminal) session for interactive commands
     * Create PTY session
     */
    async createPTYSessionRaw(requestParameters: CreatePTYSessionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreatePTYSession200Response>> {
        const requestOptions = await this.createPTYSessionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreatePTYSession200ResponseFromJSON(jsonValue));
    }

    /**
     * Create a new PTY (pseudo-terminal) session for interactive commands
     * Create PTY session
     */
    async createPTYSession(requestParameters: CreatePTYSessionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreatePTYSession200Response> {
        const response = await this.createPTYSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deletePTYSession without sending the request
     */
    async deletePTYSessionRequestOpts(requestParameters: DeletePTYSessionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deletePTYSession().'
            );
        }

        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling deletePTYSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/{id}/pty/sessions/{sessionId}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace('{sessionId}', encodeURIComponent(String(requestParameters['sessionId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Close and delete a PTY session
     * Delete PTY session
     */
    async deletePTYSessionRaw(requestParameters: DeletePTYSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessResponse>> {
        const requestOptions = await this.deletePTYSessionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessResponseFromJSON(jsonValue));
    }

    /**
     * Close and delete a PTY session
     * Delete PTY session
     */
    async deletePTYSession(requestParameters: DeletePTYSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessResponse> {
        const response = await this.deletePTYSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for execCommand without sending the request
     */
    async execCommandRequestOpts(requestParameters: ExecCommandRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling execCommand().'
            );
        }

        if (requestParameters['execRequest'] == null) {
            throw new runtime.RequiredError(
                'execRequest',
                'Required parameter "execRequest" was null or undefined when calling execCommand().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/{id}/exec`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ExecRequestToJSON(requestParameters['execRequest']),
        };
    }

    /**
     * Execute a command in the sandbox and wait for the result. For a non-blocking start with a PID, use `POST /sandboxes/{id}/commands/run`.
     * Execute command (synchronous)
     */
    async execCommandRaw(requestParameters: ExecCommandRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExecResponse>> {
        const requestOptions = await this.execCommandRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExecResponseFromJSON(jsonValue));
    }

    /**
     * Execute a command in the sandbox and wait for the result. For a non-blocking start with a PID, use `POST /sandboxes/{id}/commands/run`.
     * Execute command (synchronous)
     */
    async execCommand(requestParameters: ExecCommandRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExecResponse> {
        const response = await this.execCommandRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for execCommandStream without sending the request
     */
    async execCommandStreamRequestOpts(requestParameters: ExecCommandStreamRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling execCommandStream().'
            );
        }

        if (requestParameters['execRequest'] == null) {
            throw new runtime.RequiredError(
                'execRequest',
                'Required parameter "execRequest" was null or undefined when calling execCommandStream().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/{id}/exec-stream`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ExecRequestToJSON(requestParameters['execRequest']),
        };
    }

    /**
     * Execute a command and stream output as Server-Sent Events. Events: `stdout`, `stderr`, and final `exit`. 
     * Execute command (SSE stream)
     */
    async execCommandStreamRaw(requestParameters: ExecCommandStreamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.execCommandStreamRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Execute a command and stream output as Server-Sent Events. Events: `stdout`, `stderr`, and final `exit`. 
     * Execute command (SSE stream)
     */
    async execCommandStream(requestParameters: ExecCommandStreamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.execCommandStreamRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for executeInPTYSession without sending the request
     */
    async executeInPTYSessionRequestOpts(requestParameters: ExecuteInPTYSessionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling executeInPTYSession().'
            );
        }

        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling executeInPTYSession().'
            );
        }

        if (requestParameters['executeInSessionRequest'] == null) {
            throw new runtime.RequiredError(
                'executeInSessionRequest',
                'Required parameter "executeInSessionRequest" was null or undefined when calling executeInPTYSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/{id}/pty/sessions/{sessionId}/execute`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace('{sessionId}', encodeURIComponent(String(requestParameters['sessionId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ExecuteInSessionRequestToJSON(requestParameters['executeInSessionRequest']),
        };
    }

    /**
     * Execute a command asynchronously in an existing PTY session
     * Execute command in PTY session
     */
    async executeInPTYSessionRaw(requestParameters: ExecuteInPTYSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessResponse>> {
        const requestOptions = await this.executeInPTYSessionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessResponseFromJSON(jsonValue));
    }

    /**
     * Execute a command asynchronously in an existing PTY session
     * Execute command in PTY session
     */
    async executeInPTYSession(requestParameters: ExecuteInPTYSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessResponse> {
        const response = await this.executeInPTYSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPTYBuffer without sending the request
     */
    async getPTYBufferRequestOpts(requestParameters: GetPTYBufferRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getPTYBuffer().'
            );
        }

        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling getPTYBuffer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/{id}/pty/sessions/{sessionId}/buffer`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace('{sessionId}', encodeURIComponent(String(requestParameters['sessionId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get the current output buffer from a PTY session
     * Get output buffer
     */
    async getPTYBufferRaw(requestParameters: GetPTYBufferRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetPTYBuffer200Response>> {
        const requestOptions = await this.getPTYBufferRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetPTYBuffer200ResponseFromJSON(jsonValue));
    }

    /**
     * Get the current output buffer from a PTY session
     * Get output buffer
     */
    async getPTYBuffer(requestParameters: GetPTYBufferRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetPTYBuffer200Response> {
        const response = await this.getPTYBufferRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for killBackgroundProcess without sending the request
     */
    async killBackgroundProcessRequestOpts(requestParameters: KillBackgroundProcessOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling killBackgroundProcess().'
            );
        }

        if (requestParameters['killBackgroundProcessRequest'] == null) {
            throw new runtime.RequiredError(
                'killBackgroundProcessRequest',
                'Required parameter "killBackgroundProcessRequest" was null or undefined when calling killBackgroundProcess().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/{id}/commands/kill`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: KillBackgroundProcessRequestToJSON(requestParameters['killBackgroundProcessRequest']),
        };
    }

    /**
     * Terminate a running background process by PID
     * Kill background process
     */
    async killBackgroundProcessRaw(requestParameters: KillBackgroundProcessOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommandKillResponse>> {
        const requestOptions = await this.killBackgroundProcessRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommandKillResponseFromJSON(jsonValue));
    }

    /**
     * Terminate a running background process by PID
     * Kill background process
     */
    async killBackgroundProcess(requestParameters: KillBackgroundProcessOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommandKillResponse> {
        const response = await this.killBackgroundProcessRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listBackgroundProcesses without sending the request
     */
    async listBackgroundProcessesRequestOpts(requestParameters: ListBackgroundProcessesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listBackgroundProcesses().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/{id}/commands/list`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get list of all running background processes in the sandbox
     * List running processes
     */
    async listBackgroundProcessesRaw(requestParameters: ListBackgroundProcessesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommandListResponse>> {
        const requestOptions = await this.listBackgroundProcessesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommandListResponseFromJSON(jsonValue));
    }

    /**
     * Get list of all running background processes in the sandbox
     * List running processes
     */
    async listBackgroundProcesses(requestParameters: ListBackgroundProcessesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommandListResponse> {
        const response = await this.listBackgroundProcessesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listPTYSessions without sending the request
     */
    async listPTYSessionsRequestOpts(requestParameters: ListPTYSessionsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listPTYSessions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/{id}/pty/sessions`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all active PTY sessions for a sandbox
     * List PTY sessions
     */
    async listPTYSessionsRaw(requestParameters: ListPTYSessionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListPTYSessions200Response>> {
        const requestOptions = await this.listPTYSessionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListPTYSessions200ResponseFromJSON(jsonValue));
    }

    /**
     * Get all active PTY sessions for a sandbox
     * List PTY sessions
     */
    async listPTYSessions(requestParameters: ListPTYSessionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListPTYSessions200Response> {
        const response = await this.listPTYSessionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for resizeTerminal without sending the request
     */
    async resizeTerminalRequestOpts(requestParameters: ResizeTerminalOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling resizeTerminal().'
            );
        }

        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling resizeTerminal().'
            );
        }

        if (requestParameters['resizeTerminalRequest'] == null) {
            throw new runtime.RequiredError(
                'resizeTerminalRequest',
                'Required parameter "resizeTerminalRequest" was null or undefined when calling resizeTerminal().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/{id}/pty/sessions/{sessionId}/resize`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace('{sessionId}', encodeURIComponent(String(requestParameters['sessionId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ResizeTerminalRequestToJSON(requestParameters['resizeTerminalRequest']),
        };
    }

    /**
     * Resize the terminal dimensions for a PTY session
     * Resize terminal
     */
    async resizeTerminalRaw(requestParameters: ResizeTerminalOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessResponse>> {
        const requestOptions = await this.resizeTerminalRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessResponseFromJSON(jsonValue));
    }

    /**
     * Resize the terminal dimensions for a PTY session
     * Resize terminal
     */
    async resizeTerminal(requestParameters: ResizeTerminalOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessResponse> {
        const response = await this.resizeTerminalRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for runBackgroundCommand without sending the request
     */
    async runBackgroundCommandRequestOpts(requestParameters: RunBackgroundCommandOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling runBackgroundCommand().'
            );
        }

        if (requestParameters['runBackgroundCommandRequest'] == null) {
            throw new runtime.RequiredError(
                'runBackgroundCommandRequest',
                'Required parameter "runBackgroundCommandRequest" was null or undefined when calling runBackgroundCommand().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/{id}/commands/run`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RunBackgroundCommandRequestToJSON(requestParameters['runBackgroundCommandRequest']),
        };
    }

    /**
     * Start a command as a background process and return its PID
     * Start background process
     */
    async runBackgroundCommandRaw(requestParameters: RunBackgroundCommandOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommandRunResponse>> {
        const requestOptions = await this.runBackgroundCommandRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommandRunResponseFromJSON(jsonValue));
    }

    /**
     * Start a command as a background process and return its PID
     * Start background process
     */
    async runBackgroundCommand(requestParameters: RunBackgroundCommandOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommandRunResponse> {
        const response = await this.runBackgroundCommandRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sessionExec without sending the request
     */
    async sessionExecRequestOpts(requestParameters: SessionExecOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling sessionExec().'
            );
        }

        if (requestParameters['sessionExecRequest'] == null) {
            throw new runtime.RequiredError(
                'sessionExecRequest',
                'Required parameter "sessionExecRequest" was null or undefined when calling sessionExec().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/{id}/session-exec`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SessionExecRequestToJSON(requestParameters['sessionExecRequest']),
        };
    }

    /**
     * Send a PTY session action (`create`, `exec`, `input`, `resize`, `close`) to the sandbox agent.
     * Execute PTY session action
     */
    async sessionExecRaw(requestParameters: SessionExecOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SessionExecResponse>> {
        const requestOptions = await this.sessionExecRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SessionExecResponseFromJSON(jsonValue));
    }

    /**
     * Send a PTY session action (`create`, `exec`, `input`, `resize`, `close`) to the sandbox agent.
     * Execute PTY session action
     */
    async sessionExec(requestParameters: SessionExecOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SessionExecResponse> {
        const response = await this.sessionExecRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sessionExecStream without sending the request
     */
    async sessionExecStreamRequestOpts(requestParameters: SessionExecStreamOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling sessionExecStream().'
            );
        }

        if (requestParameters['sessionExecStreamRequest'] == null) {
            throw new runtime.RequiredError(
                'sessionExecStreamRequest',
                'Required parameter "sessionExecStreamRequest" was null or undefined when calling sessionExecStream().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/{id}/session-exec-stream`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SessionExecStreamRequestToJSON(requestParameters['sessionExecStreamRequest']),
        };
    }

    /**
     * Execute a command in an existing PTY session and stream NDJSON output chunks.
     * Stream PTY session command output
     */
    async sessionExecStreamRaw(requestParameters: SessionExecStreamOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.sessionExecStreamRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Execute a command in an existing PTY session and stream NDJSON output chunks.
     * Stream PTY session command output
     */
    async sessionExecStream(requestParameters: SessionExecStreamOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.sessionExecStreamRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for waitForBackgroundProcess without sending the request
     */
    async waitForBackgroundProcessRequestOpts(requestParameters: WaitForBackgroundProcessRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling waitForBackgroundProcess().'
            );
        }

        if (requestParameters['killBackgroundProcessRequest'] == null) {
            throw new runtime.RequiredError(
                'killBackgroundProcessRequest',
                'Required parameter "killBackgroundProcessRequest" was null or undefined when calling waitForBackgroundProcess().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/{id}/commands/wait`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: KillBackgroundProcessRequestToJSON(requestParameters['killBackgroundProcessRequest']),
        };
    }

    /**
     * Block until a background process completes and return its exit code
     * Wait for process completion
     */
    async waitForBackgroundProcessRaw(requestParameters: WaitForBackgroundProcessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommandWaitResponse>> {
        const requestOptions = await this.waitForBackgroundProcessRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommandWaitResponseFromJSON(jsonValue));
    }

    /**
     * Block until a background process completes and return its exit code
     * Wait for process completion
     */
    async waitForBackgroundProcess(requestParameters: WaitForBackgroundProcessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommandWaitResponse> {
        const response = await this.waitForBackgroundProcessRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
