/* tslint:disable */
/* eslint-disable */
/**
 * VoidRun API
 * VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  APIKeyResponse,
  ErrorResponse,
  GenerateAPIKeyRequest,
  GeneratedAPIKeyResponse,
  Organization,
  SuccessResponse,
} from '../models/index';
import {
    APIKeyResponseFromJSON,
    APIKeyResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    GenerateAPIKeyRequestFromJSON,
    GenerateAPIKeyRequestToJSON,
    GeneratedAPIKeyResponseFromJSON,
    GeneratedAPIKeyResponseToJSON,
    OrganizationFromJSON,
    OrganizationToJSON,
    SuccessResponseFromJSON,
    SuccessResponseToJSON,
} from '../models/index';

export interface GenerateAPIKeyOperationRequest {
    orgId: string;
    generateAPIKeyRequest: GenerateAPIKeyRequest;
}

export interface ListAPIKeysRequest {
    orgId: string;
}

export interface RevokeAPIKeyRequest {
    orgId: string;
    keyId: string;
}

/**
 * 
 */
export class OrganizationsApi extends runtime.BaseAPI {

    /**
     * Create a new API key for the organization. The plain key is only returned once.
     * Generate new API key
     */
    async generateAPIKeyRaw(requestParameters: GenerateAPIKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GeneratedAPIKeyResponse>> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling generateAPIKey().'
            );
        }

        if (requestParameters['generateAPIKeyRequest'] == null) {
            throw new runtime.RequiredError(
                'generateAPIKeyRequest',
                'Required parameter "generateAPIKeyRequest" was null or undefined when calling generateAPIKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/orgs/{orgId}/apikeys`;
        urlPath = urlPath.replace(`{${"orgId"}}`, encodeURIComponent(String(requestParameters['orgId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GenerateAPIKeyRequestToJSON(requestParameters['generateAPIKeyRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GeneratedAPIKeyResponseFromJSON(jsonValue));
    }

    /**
     * Create a new API key for the organization. The plain key is only returned once.
     * Generate new API key
     */
    async generateAPIKey(requestParameters: GenerateAPIKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GeneratedAPIKeyResponse> {
        const response = await this.generateAPIKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the organization associated with the API key
     * Get current organization
     */
    async getCurrentOrgRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Organization>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/orgs/me`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationFromJSON(jsonValue));
    }

    /**
     * Get the organization associated with the API key
     * Get current organization
     */
    async getCurrentOrg(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Organization> {
        const response = await this.getCurrentOrgRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get all API keys for an organization
     * List API keys
     */
    async listAPIKeysRaw(requestParameters: ListAPIKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<APIKeyResponse>>> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling listAPIKeys().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/orgs/{orgId}/apikeys`;
        urlPath = urlPath.replace(`{${"orgId"}}`, encodeURIComponent(String(requestParameters['orgId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(APIKeyResponseFromJSON));
    }

    /**
     * Get all API keys for an organization
     * List API keys
     */
    async listAPIKeys(requestParameters: ListAPIKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<APIKeyResponse>> {
        const response = await this.listAPIKeysRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete/revoke an API key
     * Revoke API key
     */
    async revokeAPIKeyRaw(requestParameters: RevokeAPIKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessResponse>> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling revokeAPIKey().'
            );
        }

        if (requestParameters['keyId'] == null) {
            throw new runtime.RequiredError(
                'keyId',
                'Required parameter "keyId" was null or undefined when calling revokeAPIKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/orgs/{orgId}/apikeys/{keyId}`;
        urlPath = urlPath.replace(`{${"orgId"}}`, encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace(`{${"keyId"}}`, encodeURIComponent(String(requestParameters['keyId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessResponseFromJSON(jsonValue));
    }

    /**
     * Delete/revoke an API key
     * Revoke API key
     */
    async revokeAPIKey(requestParameters: RevokeAPIKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessResponse> {
        const response = await this.revokeAPIKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
