/* tslint:disable */
/* eslint-disable */
/**
 * VoidRun API
 * VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/version` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type APIKeyResponse,
    APIKeyResponseFromJSON,
    APIKeyResponseToJSON,
} from '../models/APIKeyResponse';
import {
    type ActivateAPIKeyRequest,
    ActivateAPIKeyRequestFromJSON,
    ActivateAPIKeyRequestToJSON,
} from '../models/ActivateAPIKeyRequest';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse';
import {
    type GenerateAPIKeyRequest,
    GenerateAPIKeyRequestFromJSON,
    GenerateAPIKeyRequestToJSON,
} from '../models/GenerateAPIKeyRequest';
import {
    type GeneratedAPIKeyResponse,
    GeneratedAPIKeyResponseFromJSON,
    GeneratedAPIKeyResponseToJSON,
} from '../models/GeneratedAPIKeyResponse';
import {
    type GetOrgUsers200Response,
    GetOrgUsers200ResponseFromJSON,
    GetOrgUsers200ResponseToJSON,
} from '../models/GetOrgUsers200Response';
import {
    type SuccessResponse,
    SuccessResponseFromJSON,
    SuccessResponseToJSON,
} from '../models/SuccessResponse';

export interface ActivateAPIKeyOperationRequest {
    keyId: string;
    activateAPIKeyRequest: ActivateAPIKeyRequest;
}

export interface GenerateAPIKeyOperationRequest {
    generateAPIKeyRequest: GenerateAPIKeyRequest;
}

export interface RevokeAPIKeyRequest {
    keyId: string;
}

export interface TouchAPIKeyRequest {
    keyId: string;
}

/**
 * 
 */
export class OrganizationsApi extends runtime.BaseAPI {

    /**
     * Creates request options for activateAPIKey without sending the request
     */
    async activateAPIKeyRequestOpts(requestParameters: ActivateAPIKeyOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['keyId'] == null) {
            throw new runtime.RequiredError(
                'keyId',
                'Required parameter "keyId" was null or undefined when calling activateAPIKey().'
            );
        }

        if (requestParameters['activateAPIKeyRequest'] == null) {
            throw new runtime.RequiredError(
                'activateAPIKeyRequest',
                'Required parameter "activateAPIKeyRequest" was null or undefined when calling activateAPIKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/orgs/apikeys/{keyId}/activate`;
        urlPath = urlPath.replace('{keyId}', encodeURIComponent(String(requestParameters['keyId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ActivateAPIKeyRequestToJSON(requestParameters['activateAPIKeyRequest']),
        };
    }

    /**
     * Toggle an API key\'s active status. The organization is derived from the API key context.
     * Activate or deactivate API key
     */
    async activateAPIKeyRaw(requestParameters: ActivateAPIKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessResponse>> {
        const requestOptions = await this.activateAPIKeyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessResponseFromJSON(jsonValue));
    }

    /**
     * Toggle an API key\'s active status. The organization is derived from the API key context.
     * Activate or deactivate API key
     */
    async activateAPIKey(requestParameters: ActivateAPIKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessResponse> {
        const response = await this.activateAPIKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for generateAPIKey without sending the request
     */
    async generateAPIKeyRequestOpts(requestParameters: GenerateAPIKeyOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['generateAPIKeyRequest'] == null) {
            throw new runtime.RequiredError(
                'generateAPIKeyRequest',
                'Required parameter "generateAPIKeyRequest" was null or undefined when calling generateAPIKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/orgs/apikeys`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GenerateAPIKeyRequestToJSON(requestParameters['generateAPIKeyRequest']),
        };
    }

    /**
     * Create a new API key for the organization. The plain key is only returned once. The organization is derived from the API key context.
     * Generate new API key
     */
    async generateAPIKeyRaw(requestParameters: GenerateAPIKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GeneratedAPIKeyResponse>> {
        const requestOptions = await this.generateAPIKeyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GeneratedAPIKeyResponseFromJSON(jsonValue));
    }

    /**
     * Create a new API key for the organization. The plain key is only returned once. The organization is derived from the API key context.
     * Generate new API key
     */
    async generateAPIKey(requestParameters: GenerateAPIKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GeneratedAPIKeyResponse> {
        const response = await this.generateAPIKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getOrgUsers without sending the request
     */
    async getOrgUsersRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/orgs/users`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get users who are members of the authenticated user\'s organization. The organization is derived from the API key context.
     * List organization users
     */
    async getOrgUsersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetOrgUsers200Response>> {
        const requestOptions = await this.getOrgUsersRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetOrgUsers200ResponseFromJSON(jsonValue));
    }

    /**
     * Get users who are members of the authenticated user\'s organization. The organization is derived from the API key context.
     * List organization users
     */
    async getOrgUsers(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetOrgUsers200Response> {
        const response = await this.getOrgUsersRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listAPIKeys without sending the request
     */
    async listAPIKeysRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/orgs/apikeys`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all API keys for the authenticated user\'s organization. The organization is derived from the API key context.
     * List API keys
     */
    async listAPIKeysRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<APIKeyResponse>>> {
        const requestOptions = await this.listAPIKeysRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(APIKeyResponseFromJSON));
    }

    /**
     * Get all API keys for the authenticated user\'s organization. The organization is derived from the API key context.
     * List API keys
     */
    async listAPIKeys(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<APIKeyResponse>> {
        const response = await this.listAPIKeysRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for revokeAPIKey without sending the request
     */
    async revokeAPIKeyRequestOpts(requestParameters: RevokeAPIKeyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['keyId'] == null) {
            throw new runtime.RequiredError(
                'keyId',
                'Required parameter "keyId" was null or undefined when calling revokeAPIKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/orgs/apikeys/{keyId}`;
        urlPath = urlPath.replace('{keyId}', encodeURIComponent(String(requestParameters['keyId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete/revoke an API key. The organization is derived from the API key context.
     * Revoke API key
     */
    async revokeAPIKeyRaw(requestParameters: RevokeAPIKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessResponse>> {
        const requestOptions = await this.revokeAPIKeyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessResponseFromJSON(jsonValue));
    }

    /**
     * Delete/revoke an API key. The organization is derived from the API key context.
     * Revoke API key
     */
    async revokeAPIKey(requestParameters: RevokeAPIKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessResponse> {
        const response = await this.revokeAPIKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for touchAPIKey without sending the request
     */
    async touchAPIKeyRequestOpts(requestParameters: TouchAPIKeyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['keyId'] == null) {
            throw new runtime.RequiredError(
                'keyId',
                'Required parameter "keyId" was null or undefined when calling touchAPIKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/orgs/apikeys/{keyId}/touch`;
        urlPath = urlPath.replace('{keyId}', encodeURIComponent(String(requestParameters['keyId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Update the API key last-used timestamp. The organization is derived from the API key context.
     * Touch API key
     */
    async touchAPIKeyRaw(requestParameters: TouchAPIKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessResponse>> {
        const requestOptions = await this.touchAPIKeyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessResponseFromJSON(jsonValue));
    }

    /**
     * Update the API key last-used timestamp. The organization is derived from the API key context.
     * Touch API key
     */
    async touchAPIKey(requestParameters: TouchAPIKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessResponse> {
        const response = await this.touchAPIKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
