/* tslint:disable */
/* eslint-disable */
/**
 * VoidRun API
 * VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiResponseSandbox,
  ApiResponseSandboxesList,
  CreateSandbox201Response,
  CreateSandboxRequest,
  ErrorResponse,
  RestoreSandboxRequest,
  Sandbox,
  Snapshot,
  SuccessResponse,
} from '../models/index';
import {
    ApiResponseSandboxFromJSON,
    ApiResponseSandboxToJSON,
    ApiResponseSandboxesListFromJSON,
    ApiResponseSandboxesListToJSON,
    CreateSandbox201ResponseFromJSON,
    CreateSandbox201ResponseToJSON,
    CreateSandboxRequestFromJSON,
    CreateSandboxRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    RestoreSandboxRequestFromJSON,
    RestoreSandboxRequestToJSON,
    SandboxFromJSON,
    SandboxToJSON,
    SnapshotFromJSON,
    SnapshotToJSON,
    SuccessResponseFromJSON,
    SuccessResponseToJSON,
} from '../models/index';

export interface CreateSandboxOperationRequest {
    createSandboxRequest: CreateSandboxRequest;
}

export interface CreateSnapshotRequest {
    id: string;
}

export interface DeleteSandboxRequest {
    id: string;
}

export interface GetSandboxRequest {
    id: string;
}

export interface ListSandboxesRequest {
    page?: number;
    limit?: number;
}

export interface ListSnapshotsRequest {
    id: string;
}

export interface PauseSandboxRequest {
    id: string;
}

export interface RestoreSandboxOperationRequest {
    restoreSandboxRequest: RestoreSandboxRequest;
}

export interface ResumeSandboxRequest {
    id: string;
}

export interface StartSandboxRequest {
    id: string;
}

export interface StopSandboxRequest {
    id: string;
}

/**
 * 
 */
export class SandboxesApi extends runtime.BaseAPI {

    /**
     * Create a new virtual machine sandbox
     * Create sandbox
     */
    async createSandboxRaw(requestParameters: CreateSandboxOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateSandbox201Response>> {
        if (requestParameters['createSandboxRequest'] == null) {
            throw new runtime.RequiredError(
                'createSandboxRequest',
                'Required parameter "createSandboxRequest" was null or undefined when calling createSandbox().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSandboxRequestToJSON(requestParameters['createSandboxRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateSandbox201ResponseFromJSON(jsonValue));
    }

    /**
     * Create a new virtual machine sandbox
     * Create sandbox
     */
    async createSandbox(requestParameters: CreateSandboxOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateSandbox201Response> {
        const response = await this.createSandboxRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a snapshot of the sandbox
     * Create snapshot
     */
    async createSnapshotRaw(requestParameters: CreateSnapshotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createSnapshot().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/{id}/snapshot`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessResponseFromJSON(jsonValue));
    }

    /**
     * Create a snapshot of the sandbox
     * Create snapshot
     */
    async createSnapshot(requestParameters: CreateSnapshotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessResponse> {
        const response = await this.createSnapshotRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a sandbox and all its resources
     * Delete sandbox
     */
    async deleteSandboxRaw(requestParameters: DeleteSandboxRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteSandbox().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessResponseFromJSON(jsonValue));
    }

    /**
     * Delete a sandbox and all its resources
     * Delete sandbox
     */
    async deleteSandbox(requestParameters: DeleteSandboxRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessResponse> {
        const response = await this.deleteSandboxRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get detailed information about a specific sandbox
     * Get sandbox details
     */
    async getSandboxRaw(requestParameters: GetSandboxRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseSandbox>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getSandbox().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseSandboxFromJSON(jsonValue));
    }

    /**
     * Get detailed information about a specific sandbox
     * Get sandbox details
     */
    async getSandbox(requestParameters: GetSandboxRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseSandbox> {
        const response = await this.getSandboxRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all sandboxes for the current organization with pagination support
     * List sandboxes
     */
    async listSandboxesRaw(requestParameters: ListSandboxesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseSandboxesList>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseSandboxesListFromJSON(jsonValue));
    }

    /**
     * Get all sandboxes for the current organization with pagination support
     * List sandboxes
     */
    async listSandboxes(requestParameters: ListSandboxesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseSandboxesList> {
        const response = await this.listSandboxesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all snapshots for a sandbox
     * List snapshots
     */
    async listSnapshotsRaw(requestParameters: ListSnapshotsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Snapshot>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listSnapshots().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/{id}/snapshots`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SnapshotFromJSON));
    }

    /**
     * Get all snapshots for a sandbox
     * List snapshots
     */
    async listSnapshots(requestParameters: ListSnapshotsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Snapshot>> {
        const response = await this.listSnapshotsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Pause a running sandbox
     * Pause sandbox
     */
    async pauseSandboxRaw(requestParameters: PauseSandboxRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling pauseSandbox().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/{id}/pause`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessResponseFromJSON(jsonValue));
    }

    /**
     * Pause a running sandbox
     * Pause sandbox
     */
    async pauseSandbox(requestParameters: PauseSandboxRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessResponse> {
        const response = await this.pauseSandboxRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new sandbox from an existing snapshot
     * Restore sandbox from snapshot
     */
    async restoreSandboxRaw(requestParameters: RestoreSandboxOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Sandbox>> {
        if (requestParameters['restoreSandboxRequest'] == null) {
            throw new runtime.RequiredError(
                'restoreSandboxRequest',
                'Required parameter "restoreSandboxRequest" was null or undefined when calling restoreSandbox().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/restore`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RestoreSandboxRequestToJSON(requestParameters['restoreSandboxRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SandboxFromJSON(jsonValue));
    }

    /**
     * Create a new sandbox from an existing snapshot
     * Restore sandbox from snapshot
     */
    async restoreSandbox(requestParameters: RestoreSandboxOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Sandbox> {
        const response = await this.restoreSandboxRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Resume a paused sandbox
     * Resume sandbox
     */
    async resumeSandboxRaw(requestParameters: ResumeSandboxRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling resumeSandbox().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/{id}/resume`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessResponseFromJSON(jsonValue));
    }

    /**
     * Resume a paused sandbox
     * Resume sandbox
     */
    async resumeSandbox(requestParameters: ResumeSandboxRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessResponse> {
        const response = await this.resumeSandboxRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Start a stopped sandbox
     * Start sandbox
     */
    async startSandboxRaw(requestParameters: StartSandboxRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling startSandbox().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/{id}/start`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessResponseFromJSON(jsonValue));
    }

    /**
     * Start a stopped sandbox
     * Start sandbox
     */
    async startSandbox(requestParameters: StartSandboxRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessResponse> {
        const response = await this.startSandboxRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Stop a running sandbox
     * Stop sandbox
     */
    async stopSandboxRaw(requestParameters: StopSandboxRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling stopSandbox().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/sandboxes/{id}/stop`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessResponseFromJSON(jsonValue));
    }

    /**
     * Stop a running sandbox
     * Stop sandbox
     */
    async stopSandbox(requestParameters: StopSandboxRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessResponse> {
        const response = await this.stopSandboxRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
