/* tslint:disable */
/* eslint-disable */
/**
 * VoidRun API
 * VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` and `/api/version` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ActivateAPIKeyRequest
 */
export interface ActivateAPIKeyRequest {
    /**
     * 
     * @type {boolean}
     * @memberof ActivateAPIKeyRequest
     */
    isActive?: boolean;
}

/**
 * Check if a given object implements the ActivateAPIKeyRequest interface.
 */
export function instanceOfActivateAPIKeyRequest(value: object): value is ActivateAPIKeyRequest {
    return true;
}

export function ActivateAPIKeyRequestFromJSON(json: any): ActivateAPIKeyRequest {
    return ActivateAPIKeyRequestFromJSONTyped(json, false);
}

export function ActivateAPIKeyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivateAPIKeyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
    };
}

export function ActivateAPIKeyRequestToJSON(json: any): ActivateAPIKeyRequest {
    return ActivateAPIKeyRequestToJSONTyped(json, false);
}

export function ActivateAPIKeyRequestToJSONTyped(value?: ActivateAPIKeyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isActive': value['isActive'],
    };
}

