/* tslint:disable */
/* eslint-disable */
/**
 * Hyper Fleet Native API
 * Hyper Fleet Native API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface APIKeyResponse
 */
export interface APIKeyResponse {
    /**
     * 
     * @type {string}
     * @memberof APIKeyResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof APIKeyResponse
     */
    orgId?: string;
    /**
     * 
     * @type {string}
     * @memberof APIKeyResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof APIKeyResponse
     */
    createdBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof APIKeyResponse
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof APIKeyResponse
     */
    lastUsedAt?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof APIKeyResponse
     */
    isActive?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof APIKeyResponse
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the APIKeyResponse interface.
 */
export function instanceOfAPIKeyResponse(value: object): value is APIKeyResponse {
    return true;
}

export function APIKeyResponseFromJSON(json: any): APIKeyResponse {
    return APIKeyResponseFromJSONTyped(json, false);
}

export function APIKeyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): APIKeyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'orgId': json['orgId'] == null ? undefined : json['orgId'],
        'name': json['name'] == null ? undefined : json['name'],
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'lastUsedAt': json['lastUsedAt'] == null ? undefined : (new Date(json['lastUsedAt'])),
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function APIKeyResponseToJSON(json: any): APIKeyResponse {
    return APIKeyResponseToJSONTyped(json, false);
}

export function APIKeyResponseToJSONTyped(value?: APIKeyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'orgId': value['orgId'],
        'name': value['name'],
        'createdBy': value['createdBy'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'lastUsedAt': value['lastUsedAt'] == null ? value['lastUsedAt'] : value['lastUsedAt'].toISOString(),
        'isActive': value['isActive'],
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

