/* tslint:disable */
/* eslint-disable */
/**
 * VoidRun API
 * VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Sandbox } from './Sandbox';
import {
    SandboxFromJSON,
    SandboxFromJSONTyped,
    SandboxToJSON,
    SandboxToJSONTyped,
} from './Sandbox';

/**
 * 
 * @export
 * @interface ApiResponseSandbox
 */
export interface ApiResponseSandbox {
    /**
     * 
     * @type {boolean}
     * @memberof ApiResponseSandbox
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseSandbox
     */
    message?: string | null;
    /**
     * 
     * @type {Sandbox}
     * @memberof ApiResponseSandbox
     */
    data?: Sandbox;
}

/**
 * Check if a given object implements the ApiResponseSandbox interface.
 */
export function instanceOfApiResponseSandbox(value: object): value is ApiResponseSandbox {
    return true;
}

export function ApiResponseSandboxFromJSON(json: any): ApiResponseSandbox {
    return ApiResponseSandboxFromJSONTyped(json, false);
}

export function ApiResponseSandboxFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseSandbox {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : SandboxFromJSON(json['data']),
    };
}

export function ApiResponseSandboxToJSON(json: any): ApiResponseSandbox {
    return ApiResponseSandboxToJSONTyped(json, false);
}

export function ApiResponseSandboxToJSONTyped(value?: ApiResponseSandbox | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'data': SandboxToJSON(value['data']),
    };
}

