/* tslint:disable */
/* eslint-disable */
/**
 * VoidRun API
 * VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiResponseSandboxesListMeta } from './ApiResponseSandboxesListMeta';
import {
    ApiResponseSandboxesListMetaFromJSON,
    ApiResponseSandboxesListMetaFromJSONTyped,
    ApiResponseSandboxesListMetaToJSON,
    ApiResponseSandboxesListMetaToJSONTyped,
} from './ApiResponseSandboxesListMeta';
import type { Sandbox } from './Sandbox';
import {
    SandboxFromJSON,
    SandboxFromJSONTyped,
    SandboxToJSON,
    SandboxToJSONTyped,
} from './Sandbox';

/**
 * 
 * @export
 * @interface ApiResponseSandboxesList
 */
export interface ApiResponseSandboxesList {
    /**
     * 
     * @type {string}
     * @memberof ApiResponseSandboxesList
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseSandboxesList
     */
    message?: string;
    /**
     * 
     * @type {Array<Sandbox>}
     * @memberof ApiResponseSandboxesList
     */
    data?: Array<Sandbox>;
    /**
     * 
     * @type {ApiResponseSandboxesListMeta}
     * @memberof ApiResponseSandboxesList
     */
    meta?: ApiResponseSandboxesListMeta;
}

/**
 * Check if a given object implements the ApiResponseSandboxesList interface.
 */
export function instanceOfApiResponseSandboxesList(value: object): value is ApiResponseSandboxesList {
    return true;
}

export function ApiResponseSandboxesListFromJSON(json: any): ApiResponseSandboxesList {
    return ApiResponseSandboxesListFromJSONTyped(json, false);
}

export function ApiResponseSandboxesListFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseSandboxesList {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(SandboxFromJSON)),
        'meta': json['meta'] == null ? undefined : ApiResponseSandboxesListMetaFromJSON(json['meta']),
    };
}

export function ApiResponseSandboxesListToJSON(json: any): ApiResponseSandboxesList {
    return ApiResponseSandboxesListToJSONTyped(json, false);
}

export function ApiResponseSandboxesListToJSONTyped(value?: ApiResponseSandboxesList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'message': value['message'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(SandboxToJSON)),
        'meta': ApiResponseSandboxesListMetaToJSON(value['meta']),
    };
}

