/* tslint:disable */
/* eslint-disable */
/**
 * Hyper Fleet Native API
 * Hyper Fleet Native API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiResponseSandboxesListMeta
 */
export interface ApiResponseSandboxesListMeta {
    /**
     * Current page number
     * @type {number}
     * @memberof ApiResponseSandboxesListMeta
     */
    page?: number;
    /**
     * Number of items per page (actual page size used)
     * @type {number}
     * @memberof ApiResponseSandboxesListMeta
     */
    limit?: number;
    /**
     * Total number of sandboxes
     * @type {number}
     * @memberof ApiResponseSandboxesListMeta
     */
    total?: number;
    /**
     * Total number of pages
     * @type {number}
     * @memberof ApiResponseSandboxesListMeta
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the ApiResponseSandboxesListMeta interface.
 */
export function instanceOfApiResponseSandboxesListMeta(value: object): value is ApiResponseSandboxesListMeta {
    return true;
}

export function ApiResponseSandboxesListMetaFromJSON(json: any): ApiResponseSandboxesListMeta {
    return ApiResponseSandboxesListMetaFromJSONTyped(json, false);
}

export function ApiResponseSandboxesListMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseSandboxesListMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : json['page'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'total': json['total'] == null ? undefined : json['total'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function ApiResponseSandboxesListMetaToJSON(json: any): ApiResponseSandboxesListMeta {
    return ApiResponseSandboxesListMetaToJSONTyped(json, false);
}

export function ApiResponseSandboxesListMetaToJSONTyped(value?: ApiResponseSandboxesListMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'limit': value['limit'],
        'total': value['total'],
        'totalPages': value['totalPages'],
    };
}

