/* tslint:disable */
/* eslint-disable */
/**
 * Hyper Fleet Native API
 * Hyper Fleet Native API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProcessInfo } from './ProcessInfo';
import {
    ProcessInfoFromJSON,
    ProcessInfoFromJSONTyped,
    ProcessInfoToJSON,
    ProcessInfoToJSONTyped,
} from './ProcessInfo';

/**
 * 
 * @export
 * @interface CommandListResponse
 */
export interface CommandListResponse {
    /**
     * 
     * @type {boolean}
     * @memberof CommandListResponse
     */
    success?: boolean;
    /**
     * 
     * @type {Array<ProcessInfo>}
     * @memberof CommandListResponse
     */
    processes?: Array<ProcessInfo>;
}

/**
 * Check if a given object implements the CommandListResponse interface.
 */
export function instanceOfCommandListResponse(value: object): value is CommandListResponse {
    return true;
}

export function CommandListResponseFromJSON(json: any): CommandListResponse {
    return CommandListResponseFromJSONTyped(json, false);
}

export function CommandListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommandListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'processes': json['processes'] == null ? undefined : ((json['processes'] as Array<any>).map(ProcessInfoFromJSON)),
    };
}

export function CommandListResponseToJSON(json: any): CommandListResponse {
    return CommandListResponseToJSONTyped(json, false);
}

export function CommandListResponseToJSONTyped(value?: CommandListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'processes': value['processes'] == null ? undefined : ((value['processes'] as Array<any>).map(ProcessInfoToJSON)),
    };
}

