/* tslint:disable */
/* eslint-disable */
/**
 * Hyper Fleet Native API
 * Hyper Fleet Native API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommandWaitResponse
 */
export interface CommandWaitResponse {
    /**
     * 
     * @type {boolean}
     * @memberof CommandWaitResponse
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CommandWaitResponse
     */
    exitCode?: number;
    /**
     * 
     * @type {string}
     * @memberof CommandWaitResponse
     */
    error?: string | null;
}

/**
 * Check if a given object implements the CommandWaitResponse interface.
 */
export function instanceOfCommandWaitResponse(value: object): value is CommandWaitResponse {
    return true;
}

export function CommandWaitResponseFromJSON(json: any): CommandWaitResponse {
    return CommandWaitResponseFromJSONTyped(json, false);
}

export function CommandWaitResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommandWaitResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'exitCode': json['exitCode'] == null ? undefined : json['exitCode'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function CommandWaitResponseToJSON(json: any): CommandWaitResponse {
    return CommandWaitResponseToJSONTyped(json, false);
}

export function CommandWaitResponseToJSONTyped(value?: CommandWaitResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'exitCode': value['exitCode'],
        'error': value['error'],
    };
}

