/* tslint:disable */
/* eslint-disable */
/**
 * Hyper Fleet Native API
 * Hyper Fleet Native API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommandKillResponse
 */
export interface CommandKillResponse {
    /**
     * 
     * @type {boolean}
     * @memberof CommandKillResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CommandKillResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the CommandKillResponse interface.
 */
export function instanceOfCommandKillResponse(value: object): value is CommandKillResponse {
    return true;
}

export function CommandKillResponseFromJSON(json: any): CommandKillResponse {
    return CommandKillResponseFromJSONTyped(json, false);
}

export function CommandKillResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommandKillResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function CommandKillResponseToJSON(json: any): CommandKillResponse {
    return CommandKillResponseToJSONTyped(json, false);
}

export function CommandKillResponseToJSONTyped(value?: CommandKillResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
    };
}

