/* tslint:disable */
/* eslint-disable */
/**
 * Hyper Fleet Native API
 * Hyper Fleet Native API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommandRunResponse
 */
export interface CommandRunResponse {
    /**
     * 
     * @type {boolean}
     * @memberof CommandRunResponse
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CommandRunResponse
     */
    pid?: number;
    /**
     * 
     * @type {string}
     * @memberof CommandRunResponse
     */
    command?: string;
}

/**
 * Check if a given object implements the CommandRunResponse interface.
 */
export function instanceOfCommandRunResponse(value: object): value is CommandRunResponse {
    return true;
}

export function CommandRunResponseFromJSON(json: any): CommandRunResponse {
    return CommandRunResponseFromJSONTyped(json, false);
}

export function CommandRunResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommandRunResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'pid': json['pid'] == null ? undefined : json['pid'],
        'command': json['command'] == null ? undefined : json['command'],
    };
}

export function CommandRunResponseToJSON(json: any): CommandRunResponse {
    return CommandRunResponseToJSONTyped(json, false);
}

export function CommandRunResponseToJSONTyped(value?: CommandRunResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'pid': value['pid'],
        'command': value['command'],
    };
}

