/* tslint:disable */
/* eslint-disable */
/**
 * Hyper Fleet Native API
 * Hyper Fleet Native API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompressRequest
 */
export interface CompressRequest {
    /**
     * 
     * @type {string}
     * @memberof CompressRequest
     */
    path: string;
    /**
     * 
     * @type {string}
     * @memberof CompressRequest
     */
    format?: CompressRequestFormatEnum;
}


/**
 * @export
 */
export const CompressRequestFormatEnum = {
    Tar: 'tar',
    TarGz: 'tar.gz',
    TarBz2: 'tar.bz2',
    Zip: 'zip'
} as const;
export type CompressRequestFormatEnum = typeof CompressRequestFormatEnum[keyof typeof CompressRequestFormatEnum];


/**
 * Check if a given object implements the CompressRequest interface.
 */
export function instanceOfCompressRequest(value: object): value is CompressRequest {
    if (!('path' in value) || value['path'] === undefined) return false;
    return true;
}

export function CompressRequestFromJSON(json: any): CompressRequest {
    return CompressRequestFromJSONTyped(json, false);
}

export function CompressRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompressRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'path': json['path'],
        'format': json['format'] == null ? undefined : json['format'],
    };
}

export function CompressRequestToJSON(json: any): CompressRequest {
    return CompressRequestToJSONTyped(json, false);
}

export function CompressRequestToJSONTyped(value?: CompressRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'path': value['path'],
        'format': value['format'],
    };
}

