/* tslint:disable */
/* eslint-disable */
/**
 * VoidRun API
 * VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/version` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSandboxRequest
 */
export interface CreateSandboxRequest {
    /**
     * DNS-1123 subdomain format
     * @type {string}
     * @memberof CreateSandboxRequest
     */
    name: string;
    /**
     * Image name in `name:ver` or `name` format. If omitted, defaults to the latest active `code` image.
     * @type {string}
     * @memberof CreateSandboxRequest
     */
    image?: string;
    /**
     * Number of vCPUs
     * @type {number}
     * @memberof CreateSandboxRequest
     */
    cpu?: number;
    /**
     * Memory in MiB
     * @type {number}
     * @memberof CreateSandboxRequest
     */
    mem?: number;
    /**
     * Organization that owns the sandbox. When omitted, derived from the authenticated API key (the key's org). When provided, must match the key's organization or the request is rejected.
     * @type {string}
     * @memberof CreateSandboxRequest
     */
    orgId?: string;
    /**
     * User attributed as the sandbox creator. When omitted, derived from the API key (typically the key creator). When provided, must be an owner or member of the resolved org or the request is rejected.
     * @type {string}
     * @memberof CreateSandboxRequest
     */
    userId?: string;
    /**
     * If true (default), creation blocks until the agent responds (fast readiness check, ~2s timeout)
     * @type {boolean}
     * @memberof CreateSandboxRequest
     */
    sync?: boolean;
    /**
     * Environment variables to set on the sandbox
     * @type {{ [key: string]: string; }}
     * @memberof CreateSandboxRequest
     */
    envVars?: { [key: string]: string; };
    /**
     * If true, the sandbox is auto-snapshotted after idle and wakes on the next request
     * @type {boolean}
     * @memberof CreateSandboxRequest
     */
    autoSleep?: boolean;
    /**
     * Target region for the sandbox
     * @type {string}
     * @memberof CreateSandboxRequest
     */
    region?: string;
    /**
     * Sandbox ports to expose through the public gateway. Each entry is published as a separate public URL once the VM is running.
     * @type {Array<number>}
     * @memberof CreateSandboxRequest
     */
    publishPorts?: Array<number>;
    /**
     * Key-value labels attached at creation. Immutable after the sandbox is created. Max 5 labels; keys and values may each contain up to 20 characters. Keys match `^[a-z0-9]([-a-z0-9_]*[a-z0-9])?$`; neither keys nor values may contain `,` or `=`.
     * @type {{ [key: string]: string; }}
     * @memberof CreateSandboxRequest
     */
    labels?: { [key: string]: string; };
}

/**
 * Check if a given object implements the CreateSandboxRequest interface.
 */
export function instanceOfCreateSandboxRequest(value: object): value is CreateSandboxRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateSandboxRequestFromJSON(json: any): CreateSandboxRequest {
    return CreateSandboxRequestFromJSONTyped(json, false);
}

export function CreateSandboxRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSandboxRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'image': json['image'] == null ? undefined : json['image'],
        'cpu': json['cpu'] == null ? undefined : json['cpu'],
        'mem': json['mem'] == null ? undefined : json['mem'],
        'orgId': json['orgId'] == null ? undefined : json['orgId'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'sync': json['sync'] == null ? undefined : json['sync'],
        'envVars': json['envVars'] == null ? undefined : json['envVars'],
        'autoSleep': json['autoSleep'] == null ? undefined : json['autoSleep'],
        'region': json['region'] == null ? undefined : json['region'],
        'publishPorts': json['publishPorts'] == null ? undefined : json['publishPorts'],
        'labels': json['labels'] == null ? undefined : json['labels'],
    };
}

export function CreateSandboxRequestToJSON(json: any): CreateSandboxRequest {
    return CreateSandboxRequestToJSONTyped(json, false);
}

export function CreateSandboxRequestToJSONTyped(value?: CreateSandboxRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'image': value['image'],
        'cpu': value['cpu'],
        'mem': value['mem'],
        'orgId': value['orgId'],
        'userId': value['userId'],
        'sync': value['sync'],
        'envVars': value['envVars'],
        'autoSleep': value['autoSleep'],
        'region': value['region'],
        'publishPorts': value['publishPorts'],
        'labels': value['labels'],
    };
}

