/* tslint:disable */
/* eslint-disable */
/**
 * VoidRun API
 * VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreatePTYSession200ResponseAllOfData } from './CreatePTYSession200ResponseAllOfData';
import {
    CreatePTYSession200ResponseAllOfDataFromJSON,
    CreatePTYSession200ResponseAllOfDataFromJSONTyped,
    CreatePTYSession200ResponseAllOfDataToJSON,
    CreatePTYSession200ResponseAllOfDataToJSONTyped,
} from './CreatePTYSession200ResponseAllOfData';

/**
 * 
 * @export
 * @interface CreatePTYSession200Response
 */
export interface CreatePTYSession200Response {
    /**
     * 
     * @type {string}
     * @memberof CreatePTYSession200Response
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePTYSession200Response
     */
    message?: string;
    /**
     * 
     * @type {CreatePTYSession200ResponseAllOfData}
     * @memberof CreatePTYSession200Response
     */
    data?: CreatePTYSession200ResponseAllOfData;
}

/**
 * Check if a given object implements the CreatePTYSession200Response interface.
 */
export function instanceOfCreatePTYSession200Response(value: object): value is CreatePTYSession200Response {
    return true;
}

export function CreatePTYSession200ResponseFromJSON(json: any): CreatePTYSession200Response {
    return CreatePTYSession200ResponseFromJSONTyped(json, false);
}

export function CreatePTYSession200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePTYSession200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : CreatePTYSession200ResponseAllOfDataFromJSON(json['data']),
    };
}

export function CreatePTYSession200ResponseToJSON(json: any): CreatePTYSession200Response {
    return CreatePTYSession200ResponseToJSONTyped(json, false);
}

export function CreatePTYSession200ResponseToJSONTyped(value?: CreatePTYSession200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'message': value['message'],
        'data': CreatePTYSession200ResponseAllOfDataToJSON(value['data']),
    };
}

