/* tslint:disable */
/* eslint-disable */
/**
 * VoidRun API
 * VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePTYSessionRequest
 */
export interface CreatePTYSessionRequest {
    /**
     * 
     * @type {number}
     * @memberof CreatePTYSessionRequest
     */
    cols?: number;
    /**
     * 
     * @type {number}
     * @memberof CreatePTYSessionRequest
     */
    rows?: number;
}

/**
 * Check if a given object implements the CreatePTYSessionRequest interface.
 */
export function instanceOfCreatePTYSessionRequest(value: object): value is CreatePTYSessionRequest {
    return true;
}

export function CreatePTYSessionRequestFromJSON(json: any): CreatePTYSessionRequest {
    return CreatePTYSessionRequestFromJSONTyped(json, false);
}

export function CreatePTYSessionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePTYSessionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'cols': json['cols'] == null ? undefined : json['cols'],
        'rows': json['rows'] == null ? undefined : json['rows'],
    };
}

export function CreatePTYSessionRequestToJSON(json: any): CreatePTYSessionRequest {
    return CreatePTYSessionRequestToJSONTyped(json, false);
}

export function CreatePTYSessionRequestToJSONTyped(value?: CreatePTYSessionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cols': value['cols'],
        'rows': value['rows'],
    };
}

