/* tslint:disable */
/* eslint-disable */
/**
 * Hyper Fleet Native API
 * Hyper Fleet Native API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Sandbox } from './Sandbox';
import {
    SandboxFromJSON,
    SandboxFromJSONTyped,
    SandboxToJSON,
    SandboxToJSONTyped,
} from './Sandbox';

/**
 * 
 * @export
 * @interface CreateSandbox201Response
 */
export interface CreateSandbox201Response {
    /**
     * 
     * @type {string}
     * @memberof CreateSandbox201Response
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSandbox201Response
     */
    message?: string;
    /**
     * 
     * @type {Sandbox}
     * @memberof CreateSandbox201Response
     */
    data?: Sandbox;
}

/**
 * Check if a given object implements the CreateSandbox201Response interface.
 */
export function instanceOfCreateSandbox201Response(value: object): value is CreateSandbox201Response {
    return true;
}

export function CreateSandbox201ResponseFromJSON(json: any): CreateSandbox201Response {
    return CreateSandbox201ResponseFromJSONTyped(json, false);
}

export function CreateSandbox201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSandbox201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : SandboxFromJSON(json['data']),
    };
}

export function CreateSandbox201ResponseToJSON(json: any): CreateSandbox201Response {
    return CreateSandbox201ResponseToJSONTyped(json, false);
}

export function CreateSandbox201ResponseToJSONTyped(value?: CreateSandbox201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'message': value['message'],
        'data': SandboxToJSON(value['data']),
    };
}

