/* tslint:disable */
/* eslint-disable */
/**
 * Hyper Fleet Native API
 * Hyper Fleet Native API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateFileRequest
 */
export interface CreateFileRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateFileRequest
     */
    content?: string;
}

/**
 * Check if a given object implements the CreateFileRequest interface.
 */
export function instanceOfCreateFileRequest(value: object): value is CreateFileRequest {
    return true;
}

export function CreateFileRequestFromJSON(json: any): CreateFileRequest {
    return CreateFileRequestFromJSONTyped(json, false);
}

export function CreateFileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFileRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : json['content'],
    };
}

export function CreateFileRequestToJSON(json: any): CreateFileRequest {
    return CreateFileRequestToJSONTyped(json, false);
}

export function CreateFileRequestToJSONTyped(value?: CreateFileRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
    };
}

