/* tslint:disable */
/* eslint-disable */
/**
 * VoidRun API
 * VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateImageRequest
 */
export interface CreateImageRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateImageRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateImageRequest
     */
    version?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateImageRequest
     */
    path?: string;
}

/**
 * Check if a given object implements the CreateImageRequest interface.
 */
export function instanceOfCreateImageRequest(value: object): value is CreateImageRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateImageRequestFromJSON(json: any): CreateImageRequest {
    return CreateImageRequestFromJSONTyped(json, false);
}

export function CreateImageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateImageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'version': json['version'] == null ? undefined : json['version'],
        'path': json['path'] == null ? undefined : json['path'],
    };
}

export function CreateImageRequestToJSON(json: any): CreateImageRequest {
    return CreateImageRequestToJSONTyped(json, false);
}

export function CreateImageRequestToJSONTyped(value?: CreateImageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'version': value['version'],
        'path': value['path'],
    };
}

