/* tslint:disable */
/* eslint-disable */
/**
 * Hyper Fleet Native API
 * Hyper Fleet Native API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSandboxRequest
 */
export interface CreateSandboxRequest {
    /**
     * DNS-1123 subdomain format
     * @type {string}
     * @memberof CreateSandboxRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSandboxRequest
     */
    templateId?: string;
    /**
     * Number of vCPUs
     * @type {number}
     * @memberof CreateSandboxRequest
     */
    cpu?: number;
    /**
     * Memory in MiB
     * @type {number}
     * @memberof CreateSandboxRequest
     */
    mem?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateSandboxRequest
     */
    orgId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSandboxRequest
     */
    userId?: string;
    /**
     * If true (default), creation blocks until the agent responds (fast readiness check, ~2s timeout)
     * @type {boolean}
     * @memberof CreateSandboxRequest
     */
    sync?: boolean;
    /**
     * Environment variables to set on the sandbox
     * @type {{ [key: string]: string; }}
     * @memberof CreateSandboxRequest
     */
    envVars?: { [key: string]: string; };
}

/**
 * Check if a given object implements the CreateSandboxRequest interface.
 */
export function instanceOfCreateSandboxRequest(value: object): value is CreateSandboxRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateSandboxRequestFromJSON(json: any): CreateSandboxRequest {
    return CreateSandboxRequestFromJSONTyped(json, false);
}

export function CreateSandboxRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSandboxRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'templateId': json['templateId'] == null ? undefined : json['templateId'],
        'cpu': json['cpu'] == null ? undefined : json['cpu'],
        'mem': json['mem'] == null ? undefined : json['mem'],
        'orgId': json['orgId'] == null ? undefined : json['orgId'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'sync': json['sync'] == null ? undefined : json['sync'],
        'envVars': json['envVars'] == null ? undefined : json['envVars'],
    };
}

export function CreateSandboxRequestToJSON(json: any): CreateSandboxRequest {
    return CreateSandboxRequestToJSONTyped(json, false);
}

export function CreateSandboxRequestToJSONTyped(value?: CreateSandboxRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'templateId': value['templateId'],
        'cpu': value['cpu'],
        'mem': value['mem'],
        'orgId': value['orgId'],
        'userId': value['userId'],
        'sync': value['sync'],
        'envVars': value['envVars'],
    };
}

