/* tslint:disable */
/* eslint-disable */
/**
 * Hyper Fleet Native API
 * Hyper Fleet Native API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePTYSession200ResponseAllOfData
 */
export interface CreatePTYSession200ResponseAllOfData {
    /**
     * 
     * @type {string}
     * @memberof CreatePTYSession200ResponseAllOfData
     */
    sessionId?: string;
    /**
     * 
     * @type {Date}
     * @memberof CreatePTYSession200ResponseAllOfData
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the CreatePTYSession200ResponseAllOfData interface.
 */
export function instanceOfCreatePTYSession200ResponseAllOfData(value: object): value is CreatePTYSession200ResponseAllOfData {
    return true;
}

export function CreatePTYSession200ResponseAllOfDataFromJSON(json: any): CreatePTYSession200ResponseAllOfData {
    return CreatePTYSession200ResponseAllOfDataFromJSONTyped(json, false);
}

export function CreatePTYSession200ResponseAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePTYSession200ResponseAllOfData {
    if (json == null) {
        return json;
    }
    return {
        
        'sessionId': json['sessionId'] == null ? undefined : json['sessionId'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function CreatePTYSession200ResponseAllOfDataToJSON(json: any): CreatePTYSession200ResponseAllOfData {
    return CreatePTYSession200ResponseAllOfDataToJSONTyped(json, false);
}

export function CreatePTYSession200ResponseAllOfDataToJSONTyped(value?: CreatePTYSession200ResponseAllOfData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sessionId': value['sessionId'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

