/* tslint:disable */
/* eslint-disable */
/**
 * Hyper Fleet Native API
 * Hyper Fleet Native API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DiskUsage
 */
export interface DiskUsage {
    /**
     * 
     * @type {string}
     * @memberof DiskUsage
     */
    path?: string;
    /**
     * Size in bytes
     * @type {number}
     * @memberof DiskUsage
     */
    size?: number;
    /**
     * 
     * @type {string}
     * @memberof DiskUsage
     */
    humanReadable?: string;
}

/**
 * Check if a given object implements the DiskUsage interface.
 */
export function instanceOfDiskUsage(value: object): value is DiskUsage {
    return true;
}

export function DiskUsageFromJSON(json: any): DiskUsage {
    return DiskUsageFromJSONTyped(json, false);
}

export function DiskUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiskUsage {
    if (json == null) {
        return json;
    }
    return {
        
        'path': json['path'] == null ? undefined : json['path'],
        'size': json['size'] == null ? undefined : json['size'],
        'humanReadable': json['humanReadable'] == null ? undefined : json['humanReadable'],
    };
}

export function DiskUsageToJSON(json: any): DiskUsage {
    return DiskUsageToJSONTyped(json, false);
}

export function DiskUsageToJSONTyped(value?: DiskUsage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'path': value['path'],
        'size': value['size'],
        'humanReadable': value['humanReadable'],
    };
}

