/* tslint:disable */
/* eslint-disable */
/**
 * Hyper Fleet Native API
 * Hyper Fleet Native API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExecResponseData
 */
export interface ExecResponseData {
    /**
     * 
     * @type {string}
     * @memberof ExecResponseData
     */
    stdout?: string;
    /**
     * 
     * @type {string}
     * @memberof ExecResponseData
     */
    stderr?: string;
    /**
     * 
     * @type {number}
     * @memberof ExecResponseData
     */
    exitCode?: number;
}

/**
 * Check if a given object implements the ExecResponseData interface.
 */
export function instanceOfExecResponseData(value: object): value is ExecResponseData {
    return true;
}

export function ExecResponseDataFromJSON(json: any): ExecResponseData {
    return ExecResponseDataFromJSONTyped(json, false);
}

export function ExecResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExecResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'stdout': json['stdout'] == null ? undefined : json['stdout'],
        'stderr': json['stderr'] == null ? undefined : json['stderr'],
        'exitCode': json['exitCode'] == null ? undefined : json['exitCode'],
    };
}

export function ExecResponseDataToJSON(json: any): ExecResponseData {
    return ExecResponseDataToJSONTyped(json, false);
}

export function ExecResponseDataToJSONTyped(value?: ExecResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'stdout': value['stdout'],
        'stderr': value['stderr'],
        'exitCode': value['exitCode'],
    };
}

