/* tslint:disable */
/* eslint-disable */
/**
 * Hyper Fleet Native API
 * Hyper Fleet Native API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExecuteInSessionRequest
 */
export interface ExecuteInSessionRequest {
    /**
     * 
     * @type {string}
     * @memberof ExecuteInSessionRequest
     */
    command: string;
}

/**
 * Check if a given object implements the ExecuteInSessionRequest interface.
 */
export function instanceOfExecuteInSessionRequest(value: object): value is ExecuteInSessionRequest {
    if (!('command' in value) || value['command'] === undefined) return false;
    return true;
}

export function ExecuteInSessionRequestFromJSON(json: any): ExecuteInSessionRequest {
    return ExecuteInSessionRequestFromJSONTyped(json, false);
}

export function ExecuteInSessionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExecuteInSessionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'command': json['command'],
    };
}

export function ExecuteInSessionRequestToJSON(json: any): ExecuteInSessionRequest {
    return ExecuteInSessionRequestToJSONTyped(json, false);
}

export function ExecuteInSessionRequestToJSONTyped(value?: ExecuteInSessionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'command': value['command'],
    };
}

