/* tslint:disable */
/* eslint-disable */
/**
 * Hyper Fleet Native API
 * Hyper Fleet Native API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExecResponseData } from './ExecResponseData';
import {
    ExecResponseDataFromJSON,
    ExecResponseDataFromJSONTyped,
    ExecResponseDataToJSON,
    ExecResponseDataToJSONTyped,
} from './ExecResponseData';

/**
 * 
 * @export
 * @interface ExecResponse
 */
export interface ExecResponse {
    /**
     * 
     * @type {string}
     * @memberof ExecResponse
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof ExecResponse
     */
    message?: string;
    /**
     * 
     * @type {ExecResponseData}
     * @memberof ExecResponse
     */
    data?: ExecResponseData;
}

/**
 * Check if a given object implements the ExecResponse interface.
 */
export function instanceOfExecResponse(value: object): value is ExecResponse {
    return true;
}

export function ExecResponseFromJSON(json: any): ExecResponse {
    return ExecResponseFromJSONTyped(json, false);
}

export function ExecResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExecResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ExecResponseDataFromJSON(json['data']),
    };
}

export function ExecResponseToJSON(json: any): ExecResponse {
    return ExecResponseToJSONTyped(json, false);
}

export function ExecResponseToJSONTyped(value?: ExecResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'message': value['message'],
        'data': ExecResponseDataToJSON(value['data']),
    };
}

