/* tslint:disable */
/* eslint-disable */
/**
 * VoidRun API
 * VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExecRequest
 */
export interface ExecRequest {
    /**
     * 
     * @type {string}
     * @memberof ExecRequest
     */
    command: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExecRequest
     */
    args?: Array<string>;
    /**
     * Timeout in seconds (ignored if background=true)
     * @type {number}
     * @memberof ExecRequest
     */
    timeout?: number;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ExecRequest
     */
    env?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof ExecRequest
     */
    cwd?: string;
    /**
     * If true, starts process in background and returns PID immediately
     * @type {boolean}
     * @memberof ExecRequest
     */
    background?: boolean;
}

/**
 * Check if a given object implements the ExecRequest interface.
 */
export function instanceOfExecRequest(value: object): value is ExecRequest {
    if (!('command' in value) || value['command'] === undefined) return false;
    return true;
}

export function ExecRequestFromJSON(json: any): ExecRequest {
    return ExecRequestFromJSONTyped(json, false);
}

export function ExecRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExecRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'command': json['command'],
        'args': json['args'] == null ? undefined : json['args'],
        'timeout': json['timeout'] == null ? undefined : json['timeout'],
        'env': json['env'] == null ? undefined : json['env'],
        'cwd': json['cwd'] == null ? undefined : json['cwd'],
        'background': json['background'] == null ? undefined : json['background'],
    };
}

export function ExecRequestToJSON(json: any): ExecRequest {
    return ExecRequestToJSONTyped(json, false);
}

export function ExecRequestToJSONTyped(value?: ExecRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'command': value['command'],
        'args': value['args'],
        'timeout': value['timeout'],
        'env': value['env'],
        'cwd': value['cwd'],
        'background': value['background'],
    };
}

