/* tslint:disable */
/* eslint-disable */
/**
 * Hyper Fleet Native API
 * Hyper Fleet Native API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExtractRequest
 */
export interface ExtractRequest {
    /**
     * 
     * @type {string}
     * @memberof ExtractRequest
     */
    archive: string;
    /**
     * 
     * @type {string}
     * @memberof ExtractRequest
     */
    dest: string;
}

/**
 * Check if a given object implements the ExtractRequest interface.
 */
export function instanceOfExtractRequest(value: object): value is ExtractRequest {
    if (!('archive' in value) || value['archive'] === undefined) return false;
    if (!('dest' in value) || value['dest'] === undefined) return false;
    return true;
}

export function ExtractRequestFromJSON(json: any): ExtractRequest {
    return ExtractRequestFromJSONTyped(json, false);
}

export function ExtractRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtractRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'archive': json['archive'],
        'dest': json['dest'],
    };
}

export function ExtractRequestToJSON(json: any): ExtractRequest {
    return ExtractRequestToJSONTyped(json, false);
}

export function ExtractRequestToJSONTyped(value?: ExtractRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'archive': value['archive'],
        'dest': value['dest'],
    };
}

