/* tslint:disable */
/* eslint-disable */
/**
 * VoidRun API
 * VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileInfo
 */
export interface FileInfo {
    /**
     * 
     * @type {string}
     * @memberof FileInfo
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof FileInfo
     */
    path?: string;
    /**
     * 
     * @type {number}
     * @memberof FileInfo
     */
    size?: number;
    /**
     * 
     * @type {string}
     * @memberof FileInfo
     */
    mode?: string;
    /**
     * 
     * @type {boolean}
     * @memberof FileInfo
     */
    isDir?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof FileInfo
     */
    modTime?: Date;
}

/**
 * Check if a given object implements the FileInfo interface.
 */
export function instanceOfFileInfo(value: object): value is FileInfo {
    return true;
}

export function FileInfoFromJSON(json: any): FileInfo {
    return FileInfoFromJSONTyped(json, false);
}

export function FileInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'path': json['path'] == null ? undefined : json['path'],
        'size': json['size'] == null ? undefined : json['size'],
        'mode': json['mode'] == null ? undefined : json['mode'],
        'isDir': json['isDir'] == null ? undefined : json['isDir'],
        'modTime': json['modTime'] == null ? undefined : (new Date(json['modTime'])),
    };
}

export function FileInfoToJSON(json: any): FileInfo {
    return FileInfoToJSONTyped(json, false);
}

export function FileInfoToJSONTyped(value?: FileInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'path': value['path'],
        'size': value['size'],
        'mode': value['mode'],
        'isDir': value['isDir'],
        'modTime': value['modTime'] == null ? value['modTime'] : value['modTime'].toISOString(),
    };
}

