/* tslint:disable */
/* eslint-disable */
/**
 * VoidRun API
 * VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileStats
 */
export interface FileStats {
    /**
     * 
     * @type {string}
     * @memberof FileStats
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof FileStats
     */
    path?: string;
    /**
     * 
     * @type {number}
     * @memberof FileStats
     */
    size?: number;
    /**
     * 
     * @type {string}
     * @memberof FileStats
     */
    mode?: string;
    /**
     * 
     * @type {boolean}
     * @memberof FileStats
     */
    isDir?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof FileStats
     */
    modTime?: Date;
    /**
     * 
     * @type {number}
     * @memberof FileStats
     */
    uid?: number;
    /**
     * 
     * @type {number}
     * @memberof FileStats
     */
    gid?: number;
}

/**
 * Check if a given object implements the FileStats interface.
 */
export function instanceOfFileStats(value: object): value is FileStats {
    return true;
}

export function FileStatsFromJSON(json: any): FileStats {
    return FileStatsFromJSONTyped(json, false);
}

export function FileStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileStats {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'path': json['path'] == null ? undefined : json['path'],
        'size': json['size'] == null ? undefined : json['size'],
        'mode': json['mode'] == null ? undefined : json['mode'],
        'isDir': json['isDir'] == null ? undefined : json['isDir'],
        'modTime': json['modTime'] == null ? undefined : (new Date(json['modTime'])),
        'uid': json['uid'] == null ? undefined : json['uid'],
        'gid': json['gid'] == null ? undefined : json['gid'],
    };
}

export function FileStatsToJSON(json: any): FileStats {
    return FileStatsToJSONTyped(json, false);
}

export function FileStatsToJSONTyped(value?: FileStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'path': value['path'],
        'size': value['size'],
        'mode': value['mode'],
        'isDir': value['isDir'],
        'modTime': value['modTime'] == null ? value['modTime'] : value['modTime'].toISOString(),
        'uid': value['uid'],
        'gid': value['gid'],
    };
}

