/* tslint:disable */
/* eslint-disable */
/**
 * Hyper Fleet Native API
 * Hyper Fleet Native API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileEvent
 */
export interface FileEvent {
    /**
     * Type of filesystem event
     * @type {string}
     * @memberof FileEvent
     */
    type?: FileEventTypeEnum;
    /**
     * Absolute path to the file
     * @type {string}
     * @memberof FileEvent
     */
    path?: string;
    /**
     * Previous path for rename events (optional)
     * @type {string}
     * @memberof FileEvent
     */
    oldPath?: string;
    /**
     * File size in bytes (optional)
     * @type {number}
     * @memberof FileEvent
     */
    size?: number;
    /**
     * When the event occurred
     * @type {Date}
     * @memberof FileEvent
     */
    timestamp?: Date;
}


/**
 * @export
 */
export const FileEventTypeEnum = {
    Created: 'created',
    Modified: 'modified',
    Deleted: 'deleted',
    Renamed: 'renamed',
    Chmod: 'chmod'
} as const;
export type FileEventTypeEnum = typeof FileEventTypeEnum[keyof typeof FileEventTypeEnum];


/**
 * Check if a given object implements the FileEvent interface.
 */
export function instanceOfFileEvent(value: object): value is FileEvent {
    return true;
}

export function FileEventFromJSON(json: any): FileEvent {
    return FileEventFromJSONTyped(json, false);
}

export function FileEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'path': json['path'] == null ? undefined : json['path'],
        'oldPath': json['oldPath'] == null ? undefined : json['oldPath'],
        'size': json['size'] == null ? undefined : json['size'],
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
    };
}

export function FileEventToJSON(json: any): FileEvent {
    return FileEventToJSONTyped(json, false);
}

export function FileEventToJSONTyped(value?: FileEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'path': value['path'],
        'oldPath': value['oldPath'],
        'size': value['size'],
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
    };
}

