/* tslint:disable */
/* eslint-disable */
/**
 * Hyper Fleet Native API
 * Hyper Fleet Native API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeneratedAPIKeyResponse
 */
export interface GeneratedAPIKeyResponse {
    /**
     * Only returned once at generation time
     * @type {string}
     * @memberof GeneratedAPIKeyResponse
     */
    plainKey?: string;
    /**
     * 
     * @type {string}
     * @memberof GeneratedAPIKeyResponse
     */
    keyId?: string;
    /**
     * 
     * @type {string}
     * @memberof GeneratedAPIKeyResponse
     */
    keyName?: string;
    /**
     * 
     * @type {string}
     * @memberof GeneratedAPIKeyResponse
     */
    orgId?: string;
    /**
     * 
     * @type {Date}
     * @memberof GeneratedAPIKeyResponse
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof GeneratedAPIKeyResponse
     */
    expiresIn?: string;
}

/**
 * Check if a given object implements the GeneratedAPIKeyResponse interface.
 */
export function instanceOfGeneratedAPIKeyResponse(value: object): value is GeneratedAPIKeyResponse {
    return true;
}

export function GeneratedAPIKeyResponseFromJSON(json: any): GeneratedAPIKeyResponse {
    return GeneratedAPIKeyResponseFromJSONTyped(json, false);
}

export function GeneratedAPIKeyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratedAPIKeyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'plainKey': json['plainKey'] == null ? undefined : json['plainKey'],
        'keyId': json['keyId'] == null ? undefined : json['keyId'],
        'keyName': json['keyName'] == null ? undefined : json['keyName'],
        'orgId': json['orgId'] == null ? undefined : json['orgId'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'expiresIn': json['expiresIn'] == null ? undefined : json['expiresIn'],
    };
}

export function GeneratedAPIKeyResponseToJSON(json: any): GeneratedAPIKeyResponse {
    return GeneratedAPIKeyResponseToJSONTyped(json, false);
}

export function GeneratedAPIKeyResponseToJSONTyped(value?: GeneratedAPIKeyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'plainKey': value['plainKey'],
        'keyId': value['keyId'],
        'keyName': value['keyName'],
        'orgId': value['orgId'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'expiresIn': value['expiresIn'],
    };
}

