/* tslint:disable */
/* eslint-disable */
/**
 * VoidRun API
 * VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenerateAPIKeyRequest
 */
export interface GenerateAPIKeyRequest {
    /**
     * 
     * @type {string}
     * @memberof GenerateAPIKeyRequest
     */
    orgId: string;
    /**
     * 
     * @type {string}
     * @memberof GenerateAPIKeyRequest
     */
    keyName: string;
}

/**
 * Check if a given object implements the GenerateAPIKeyRequest interface.
 */
export function instanceOfGenerateAPIKeyRequest(value: object): value is GenerateAPIKeyRequest {
    if (!('orgId' in value) || value['orgId'] === undefined) return false;
    if (!('keyName' in value) || value['keyName'] === undefined) return false;
    return true;
}

export function GenerateAPIKeyRequestFromJSON(json: any): GenerateAPIKeyRequest {
    return GenerateAPIKeyRequestFromJSONTyped(json, false);
}

export function GenerateAPIKeyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateAPIKeyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'orgId': json['orgId'],
        'keyName': json['keyName'],
    };
}

export function GenerateAPIKeyRequestToJSON(json: any): GenerateAPIKeyRequest {
    return GenerateAPIKeyRequestToJSONTyped(json, false);
}

export function GenerateAPIKeyRequestToJSONTyped(value?: GenerateAPIKeyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orgId': value['orgId'],
        'keyName': value['keyName'],
    };
}

