/* tslint:disable */
/* eslint-disable */
/**
 * VoidRun API
 * VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/version` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetCurrentUser200ResponseOrgsInner
 */
export interface GetCurrentUser200ResponseOrgsInner {
    /**
     * 
     * @type {string}
     * @memberof GetCurrentUser200ResponseOrgsInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof GetCurrentUser200ResponseOrgsInner
     */
    name?: string;
}

/**
 * Check if a given object implements the GetCurrentUser200ResponseOrgsInner interface.
 */
export function instanceOfGetCurrentUser200ResponseOrgsInner(value: object): value is GetCurrentUser200ResponseOrgsInner {
    return true;
}

export function GetCurrentUser200ResponseOrgsInnerFromJSON(json: any): GetCurrentUser200ResponseOrgsInner {
    return GetCurrentUser200ResponseOrgsInnerFromJSONTyped(json, false);
}

export function GetCurrentUser200ResponseOrgsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCurrentUser200ResponseOrgsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function GetCurrentUser200ResponseOrgsInnerToJSON(json: any): GetCurrentUser200ResponseOrgsInner {
    return GetCurrentUser200ResponseOrgsInnerToJSONTyped(json, false);
}

export function GetCurrentUser200ResponseOrgsInnerToJSONTyped(value?: GetCurrentUser200ResponseOrgsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

