/* tslint:disable */
/* eslint-disable */
/**
 * VoidRun API
 * VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/version` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetCurrentUser200ResponseOrgsInner } from './GetCurrentUser200ResponseOrgsInner';
import {
    GetCurrentUser200ResponseOrgsInnerFromJSON,
    GetCurrentUser200ResponseOrgsInnerFromJSONTyped,
    GetCurrentUser200ResponseOrgsInnerToJSON,
    GetCurrentUser200ResponseOrgsInnerToJSONTyped,
} from './GetCurrentUser200ResponseOrgsInner';

/**
 * 
 * @export
 * @interface GetCurrentUser200Response
 */
export interface GetCurrentUser200Response {
    /**
     * 
     * @type {string}
     * @memberof GetCurrentUser200Response
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof GetCurrentUser200Response
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof GetCurrentUser200Response
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof GetCurrentUser200Response
     */
    imageUrl?: string;
    /**
     * 
     * @type {Date}
     * @memberof GetCurrentUser200Response
     */
    createdAt?: Date;
    /**
     * 
     * @type {Array<GetCurrentUser200ResponseOrgsInner>}
     * @memberof GetCurrentUser200Response
     */
    orgs?: Array<GetCurrentUser200ResponseOrgsInner>;
}

/**
 * Check if a given object implements the GetCurrentUser200Response interface.
 */
export function instanceOfGetCurrentUser200Response(value: object): value is GetCurrentUser200Response {
    return true;
}

export function GetCurrentUser200ResponseFromJSON(json: any): GetCurrentUser200Response {
    return GetCurrentUser200ResponseFromJSONTyped(json, false);
}

export function GetCurrentUser200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCurrentUser200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'orgs': json['orgs'] == null ? undefined : ((json['orgs'] as Array<any>).map(GetCurrentUser200ResponseOrgsInnerFromJSON)),
    };
}

export function GetCurrentUser200ResponseToJSON(json: any): GetCurrentUser200Response {
    return GetCurrentUser200ResponseToJSONTyped(json, false);
}

export function GetCurrentUser200ResponseToJSONTyped(value?: GetCurrentUser200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'email': value['email'],
        'imageUrl': value['imageUrl'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'orgs': value['orgs'] == null ? undefined : ((value['orgs'] as Array<any>).map(GetCurrentUser200ResponseOrgsInnerToJSON)),
    };
}

