/* tslint:disable */
/* eslint-disable */
/**
 * VoidRun API
 * VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/version` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetOrgUsers200ResponseAllOfDataInner
 */
export interface GetOrgUsers200ResponseAllOfDataInner {
    /**
     * 
     * @type {string}
     * @memberof GetOrgUsers200ResponseAllOfDataInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOrgUsers200ResponseAllOfDataInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOrgUsers200ResponseAllOfDataInner
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOrgUsers200ResponseAllOfDataInner
     */
    imageUrl?: string;
    /**
     * 
     * @type {Date}
     * @memberof GetOrgUsers200ResponseAllOfDataInner
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the GetOrgUsers200ResponseAllOfDataInner interface.
 */
export function instanceOfGetOrgUsers200ResponseAllOfDataInner(value: object): value is GetOrgUsers200ResponseAllOfDataInner {
    return true;
}

export function GetOrgUsers200ResponseAllOfDataInnerFromJSON(json: any): GetOrgUsers200ResponseAllOfDataInner {
    return GetOrgUsers200ResponseAllOfDataInnerFromJSONTyped(json, false);
}

export function GetOrgUsers200ResponseAllOfDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOrgUsers200ResponseAllOfDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function GetOrgUsers200ResponseAllOfDataInnerToJSON(json: any): GetOrgUsers200ResponseAllOfDataInner {
    return GetOrgUsers200ResponseAllOfDataInnerToJSONTyped(json, false);
}

export function GetOrgUsers200ResponseAllOfDataInnerToJSONTyped(value?: GetOrgUsers200ResponseAllOfDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'email': value['email'],
        'imageUrl': value['imageUrl'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

