/* tslint:disable */
/* eslint-disable */
/**
 * VoidRun API
 * VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/version` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetOrgUsers200ResponseAllOfDataInner } from './GetOrgUsers200ResponseAllOfDataInner';
import {
    GetOrgUsers200ResponseAllOfDataInnerFromJSON,
    GetOrgUsers200ResponseAllOfDataInnerFromJSONTyped,
    GetOrgUsers200ResponseAllOfDataInnerToJSON,
    GetOrgUsers200ResponseAllOfDataInnerToJSONTyped,
} from './GetOrgUsers200ResponseAllOfDataInner';

/**
 * 
 * @export
 * @interface GetOrgUsers200Response
 */
export interface GetOrgUsers200Response {
    /**
     * 
     * @type {string}
     * @memberof GetOrgUsers200Response
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOrgUsers200Response
     */
    message?: string;
    /**
     * 
     * @type {Array<GetOrgUsers200ResponseAllOfDataInner>}
     * @memberof GetOrgUsers200Response
     */
    data?: Array<GetOrgUsers200ResponseAllOfDataInner>;
}

/**
 * Check if a given object implements the GetOrgUsers200Response interface.
 */
export function instanceOfGetOrgUsers200Response(value: object): value is GetOrgUsers200Response {
    return true;
}

export function GetOrgUsers200ResponseFromJSON(json: any): GetOrgUsers200Response {
    return GetOrgUsers200ResponseFromJSONTyped(json, false);
}

export function GetOrgUsers200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOrgUsers200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(GetOrgUsers200ResponseAllOfDataInnerFromJSON)),
    };
}

export function GetOrgUsers200ResponseToJSON(json: any): GetOrgUsers200Response {
    return GetOrgUsers200ResponseToJSONTyped(json, false);
}

export function GetOrgUsers200ResponseToJSONTyped(value?: GetOrgUsers200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'message': value['message'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(GetOrgUsers200ResponseAllOfDataInnerToJSON)),
    };
}

