/* tslint:disable */
/* eslint-disable */
/**
 * Hyper Fleet Native API
 * Hyper Fleet Native API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetPTYBuffer200ResponseAllOfData
 */
export interface GetPTYBuffer200ResponseAllOfData {
    /**
     * 
     * @type {string}
     * @memberof GetPTYBuffer200ResponseAllOfData
     */
    output?: string;
}

/**
 * Check if a given object implements the GetPTYBuffer200ResponseAllOfData interface.
 */
export function instanceOfGetPTYBuffer200ResponseAllOfData(value: object): value is GetPTYBuffer200ResponseAllOfData {
    return true;
}

export function GetPTYBuffer200ResponseAllOfDataFromJSON(json: any): GetPTYBuffer200ResponseAllOfData {
    return GetPTYBuffer200ResponseAllOfDataFromJSONTyped(json, false);
}

export function GetPTYBuffer200ResponseAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPTYBuffer200ResponseAllOfData {
    if (json == null) {
        return json;
    }
    return {
        
        'output': json['output'] == null ? undefined : json['output'],
    };
}

export function GetPTYBuffer200ResponseAllOfDataToJSON(json: any): GetPTYBuffer200ResponseAllOfData {
    return GetPTYBuffer200ResponseAllOfDataToJSONTyped(json, false);
}

export function GetPTYBuffer200ResponseAllOfDataToJSONTyped(value?: GetPTYBuffer200ResponseAllOfData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'output': value['output'],
    };
}

