/* tslint:disable */
/* eslint-disable */
/**
 * VoidRun API
 * VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetPTYBuffer200ResponseAllOfData } from './GetPTYBuffer200ResponseAllOfData';
import {
    GetPTYBuffer200ResponseAllOfDataFromJSON,
    GetPTYBuffer200ResponseAllOfDataFromJSONTyped,
    GetPTYBuffer200ResponseAllOfDataToJSON,
    GetPTYBuffer200ResponseAllOfDataToJSONTyped,
} from './GetPTYBuffer200ResponseAllOfData';

/**
 * 
 * @export
 * @interface GetPTYBuffer200Response
 */
export interface GetPTYBuffer200Response {
    /**
     * 
     * @type {string}
     * @memberof GetPTYBuffer200Response
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof GetPTYBuffer200Response
     */
    message?: string;
    /**
     * 
     * @type {GetPTYBuffer200ResponseAllOfData}
     * @memberof GetPTYBuffer200Response
     */
    data?: GetPTYBuffer200ResponseAllOfData;
}

/**
 * Check if a given object implements the GetPTYBuffer200Response interface.
 */
export function instanceOfGetPTYBuffer200Response(value: object): value is GetPTYBuffer200Response {
    return true;
}

export function GetPTYBuffer200ResponseFromJSON(json: any): GetPTYBuffer200Response {
    return GetPTYBuffer200ResponseFromJSONTyped(json, false);
}

export function GetPTYBuffer200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPTYBuffer200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : GetPTYBuffer200ResponseAllOfDataFromJSON(json['data']),
    };
}

export function GetPTYBuffer200ResponseToJSON(json: any): GetPTYBuffer200Response {
    return GetPTYBuffer200ResponseToJSONTyped(json, false);
}

export function GetPTYBuffer200ResponseToJSONTyped(value?: GetPTYBuffer200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'message': value['message'],
        'data': GetPTYBuffer200ResponseAllOfDataToJSON(value['data']),
    };
}

