/* tslint:disable */
/* eslint-disable */
/**
 * VoidRun API
 * VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/version` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetVersion200Response
 */
export interface GetVersion200Response {
    /**
     * 
     * @type {string}
     * @memberof GetVersion200Response
     */
    version?: string;
    /**
     * 
     * @type {string}
     * @memberof GetVersion200Response
     */
    commit?: string;
    /**
     * 
     * @type {string}
     * @memberof GetVersion200Response
     */
    buildTime?: string;
}

/**
 * Check if a given object implements the GetVersion200Response interface.
 */
export function instanceOfGetVersion200Response(value: object): value is GetVersion200Response {
    return true;
}

export function GetVersion200ResponseFromJSON(json: any): GetVersion200Response {
    return GetVersion200ResponseFromJSONTyped(json, false);
}

export function GetVersion200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetVersion200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'] == null ? undefined : json['version'],
        'commit': json['commit'] == null ? undefined : json['commit'],
        'buildTime': json['buildTime'] == null ? undefined : json['buildTime'],
    };
}

export function GetVersion200ResponseToJSON(json: any): GetVersion200Response {
    return GetVersion200ResponseToJSONTyped(json, false);
}

export function GetVersion200ResponseToJSONTyped(value?: GetVersion200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': value['version'],
        'commit': value['commit'],
        'buildTime': value['buildTime'],
    };
}

