/* tslint:disable */
/* eslint-disable */
/**
 * VoidRun API
 * VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/version` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Image
 */
export interface Image {
    /**
     * 
     * @type {string}
     * @memberof Image
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Image
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Image
     */
    tag?: string;
    /**
     * Virtual size in GB
     * @type {number}
     * @memberof Image
     */
    sizeGB?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Image
     */
    system?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Image
     */
    active?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Image
     */
    orgId?: string;
    /**
     * 
     * @type {Date}
     * @memberof Image
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Image
     */
    createdBy?: string;
}

/**
 * Check if a given object implements the Image interface.
 */
export function instanceOfImage(value: object): value is Image {
    return true;
}

export function ImageFromJSON(json: any): Image {
    return ImageFromJSONTyped(json, false);
}

export function ImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Image {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'tag': json['tag'] == null ? undefined : json['tag'],
        'sizeGB': json['sizeGB'] == null ? undefined : json['sizeGB'],
        'system': json['system'] == null ? undefined : json['system'],
        'active': json['active'] == null ? undefined : json['active'],
        'orgId': json['orgId'] == null ? undefined : json['orgId'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
    };
}

export function ImageToJSON(json: any): Image {
    return ImageToJSONTyped(json, false);
}

export function ImageToJSONTyped(value?: Image | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'tag': value['tag'],
        'sizeGB': value['sizeGB'],
        'system': value['system'],
        'active': value['active'],
        'orgId': value['orgId'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'createdBy': value['createdBy'],
    };
}

