/* tslint:disable */
/* eslint-disable */
/**
 * Hyper Fleet Native API
 * Hyper Fleet Native API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KillBackgroundProcessRequest
 */
export interface KillBackgroundProcessRequest {
    /**
     * 
     * @type {number}
     * @memberof KillBackgroundProcessRequest
     */
    pid: number;
}

/**
 * Check if a given object implements the KillBackgroundProcessRequest interface.
 */
export function instanceOfKillBackgroundProcessRequest(value: object): value is KillBackgroundProcessRequest {
    if (!('pid' in value) || value['pid'] === undefined) return false;
    return true;
}

export function KillBackgroundProcessRequestFromJSON(json: any): KillBackgroundProcessRequest {
    return KillBackgroundProcessRequestFromJSONTyped(json, false);
}

export function KillBackgroundProcessRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): KillBackgroundProcessRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'pid': json['pid'],
    };
}

export function KillBackgroundProcessRequestToJSON(json: any): KillBackgroundProcessRequest {
    return KillBackgroundProcessRequestToJSONTyped(json, false);
}

export function KillBackgroundProcessRequestToJSONTyped(value?: KillBackgroundProcessRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pid': value['pid'],
    };
}

