/* tslint:disable */
/* eslint-disable */
/**
 * VoidRun API
 * VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListPTYSessions200ResponseAllOfData } from './ListPTYSessions200ResponseAllOfData';
import {
    ListPTYSessions200ResponseAllOfDataFromJSON,
    ListPTYSessions200ResponseAllOfDataFromJSONTyped,
    ListPTYSessions200ResponseAllOfDataToJSON,
    ListPTYSessions200ResponseAllOfDataToJSONTyped,
} from './ListPTYSessions200ResponseAllOfData';

/**
 * 
 * @export
 * @interface ListPTYSessions200Response
 */
export interface ListPTYSessions200Response {
    /**
     * 
     * @type {string}
     * @memberof ListPTYSessions200Response
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof ListPTYSessions200Response
     */
    message?: string;
    /**
     * 
     * @type {ListPTYSessions200ResponseAllOfData}
     * @memberof ListPTYSessions200Response
     */
    data?: ListPTYSessions200ResponseAllOfData;
}

/**
 * Check if a given object implements the ListPTYSessions200Response interface.
 */
export function instanceOfListPTYSessions200Response(value: object): value is ListPTYSessions200Response {
    return true;
}

export function ListPTYSessions200ResponseFromJSON(json: any): ListPTYSessions200Response {
    return ListPTYSessions200ResponseFromJSONTyped(json, false);
}

export function ListPTYSessions200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListPTYSessions200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ListPTYSessions200ResponseAllOfDataFromJSON(json['data']),
    };
}

export function ListPTYSessions200ResponseToJSON(json: any): ListPTYSessions200Response {
    return ListPTYSessions200ResponseToJSONTyped(json, false);
}

export function ListPTYSessions200ResponseToJSONTyped(value?: ListPTYSessions200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'message': value['message'],
        'data': ListPTYSessions200ResponseAllOfDataToJSON(value['data']),
    };
}

