/* tslint:disable */
/* eslint-disable */
/**
 * Hyper Fleet Native API
 * Hyper Fleet Native API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PTYSessionInfo } from './PTYSessionInfo';
import {
    PTYSessionInfoFromJSON,
    PTYSessionInfoFromJSONTyped,
    PTYSessionInfoToJSON,
    PTYSessionInfoToJSONTyped,
} from './PTYSessionInfo';

/**
 * 
 * @export
 * @interface ListPTYSessions200ResponseAllOfData
 */
export interface ListPTYSessions200ResponseAllOfData {
    /**
     * 
     * @type {Array<PTYSessionInfo>}
     * @memberof ListPTYSessions200ResponseAllOfData
     */
    sessions?: Array<PTYSessionInfo>;
}

/**
 * Check if a given object implements the ListPTYSessions200ResponseAllOfData interface.
 */
export function instanceOfListPTYSessions200ResponseAllOfData(value: object): value is ListPTYSessions200ResponseAllOfData {
    return true;
}

export function ListPTYSessions200ResponseAllOfDataFromJSON(json: any): ListPTYSessions200ResponseAllOfData {
    return ListPTYSessions200ResponseAllOfDataFromJSONTyped(json, false);
}

export function ListPTYSessions200ResponseAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListPTYSessions200ResponseAllOfData {
    if (json == null) {
        return json;
    }
    return {
        
        'sessions': json['sessions'] == null ? undefined : ((json['sessions'] as Array<any>).map(PTYSessionInfoFromJSON)),
    };
}

export function ListPTYSessions200ResponseAllOfDataToJSON(json: any): ListPTYSessions200ResponseAllOfData {
    return ListPTYSessions200ResponseAllOfDataToJSONTyped(json, false);
}

export function ListPTYSessions200ResponseAllOfDataToJSONTyped(value?: ListPTYSessions200ResponseAllOfData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sessions': value['sessions'] == null ? undefined : ((value['sessions'] as Array<any>).map(PTYSessionInfoToJSON)),
    };
}

