/* tslint:disable */
/* eslint-disable */
/**
 * VoidRun API
 * VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListFiles200ResponseData } from './ListFiles200ResponseData';
import {
    ListFiles200ResponseDataFromJSON,
    ListFiles200ResponseDataFromJSONTyped,
    ListFiles200ResponseDataToJSON,
    ListFiles200ResponseDataToJSONTyped,
} from './ListFiles200ResponseData';

/**
 * 
 * @export
 * @interface ListFiles200Response
 */
export interface ListFiles200Response {
    /**
     * 
     * @type {string}
     * @memberof ListFiles200Response
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof ListFiles200Response
     */
    message?: string;
    /**
     * 
     * @type {ListFiles200ResponseData}
     * @memberof ListFiles200Response
     */
    data?: ListFiles200ResponseData;
}

/**
 * Check if a given object implements the ListFiles200Response interface.
 */
export function instanceOfListFiles200Response(value: object): value is ListFiles200Response {
    return true;
}

export function ListFiles200ResponseFromJSON(json: any): ListFiles200Response {
    return ListFiles200ResponseFromJSONTyped(json, false);
}

export function ListFiles200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListFiles200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ListFiles200ResponseDataFromJSON(json['data']),
    };
}

export function ListFiles200ResponseToJSON(json: any): ListFiles200Response {
    return ListFiles200ResponseToJSONTyped(json, false);
}

export function ListFiles200ResponseToJSONTyped(value?: ListFiles200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'message': value['message'],
        'data': ListFiles200ResponseDataToJSON(value['data']),
    };
}

