/* tslint:disable */
/* eslint-disable */
/**
 * VoidRun API
 * VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileInfo } from './FileInfo';
import {
    FileInfoFromJSON,
    FileInfoFromJSONTyped,
    FileInfoToJSON,
    FileInfoToJSONTyped,
} from './FileInfo';

/**
 * 
 * @export
 * @interface ListFiles200ResponseData
 */
export interface ListFiles200ResponseData {
    /**
     * 
     * @type {boolean}
     * @memberof ListFiles200ResponseData
     */
    success?: boolean;
    /**
     * 
     * @type {Array<FileInfo>}
     * @memberof ListFiles200ResponseData
     */
    files?: Array<FileInfo>;
}

/**
 * Check if a given object implements the ListFiles200ResponseData interface.
 */
export function instanceOfListFiles200ResponseData(value: object): value is ListFiles200ResponseData {
    return true;
}

export function ListFiles200ResponseDataFromJSON(json: any): ListFiles200ResponseData {
    return ListFiles200ResponseDataFromJSONTyped(json, false);
}

export function ListFiles200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListFiles200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'files': json['files'] == null ? undefined : ((json['files'] as Array<any>).map(FileInfoFromJSON)),
    };
}

export function ListFiles200ResponseDataToJSON(json: any): ListFiles200ResponseData {
    return ListFiles200ResponseDataToJSONTyped(json, false);
}

export function ListFiles200ResponseDataToJSONTyped(value?: ListFiles200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'files': value['files'] == null ? undefined : ((value['files'] as Array<any>).map(FileInfoToJSON)),
    };
}

