/* tslint:disable */
/* eslint-disable */
/**
 * VoidRun API
 * VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProcessInfo
 */
export interface ProcessInfo {
    /**
     * 
     * @type {number}
     * @memberof ProcessInfo
     */
    pid?: number;
    /**
     * 
     * @type {string}
     * @memberof ProcessInfo
     */
    command?: string;
    /**
     * 
     * @type {Date}
     * @memberof ProcessInfo
     */
    startTime?: Date;
    /**
     * Whether the process is currently running
     * @type {boolean}
     * @memberof ProcessInfo
     */
    running?: boolean;
    /**
     * Exit code if process has finished (null if still running)
     * @type {number}
     * @memberof ProcessInfo
     */
    exitCode?: number | null;
}

/**
 * Check if a given object implements the ProcessInfo interface.
 */
export function instanceOfProcessInfo(value: object): value is ProcessInfo {
    return true;
}

export function ProcessInfoFromJSON(json: any): ProcessInfo {
    return ProcessInfoFromJSONTyped(json, false);
}

export function ProcessInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'pid': json['pid'] == null ? undefined : json['pid'],
        'command': json['command'] == null ? undefined : json['command'],
        'startTime': json['startTime'] == null ? undefined : (new Date(json['startTime'])),
        'running': json['running'] == null ? undefined : json['running'],
        'exitCode': json['exitCode'] == null ? undefined : json['exitCode'],
    };
}

export function ProcessInfoToJSON(json: any): ProcessInfo {
    return ProcessInfoToJSONTyped(json, false);
}

export function ProcessInfoToJSONTyped(value?: ProcessInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pid': value['pid'],
        'command': value['command'],
        'startTime': value['startTime'] == null ? value['startTime'] : value['startTime'].toISOString(),
        'running': value['running'],
        'exitCode': value['exitCode'],
    };
}

