/* tslint:disable */
/* eslint-disable */
/**
 * Hyper Fleet Native API
 * Hyper Fleet Native API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PTYSessionInfo
 */
export interface PTYSessionInfo {
    /**
     * 
     * @type {string}
     * @memberof PTYSessionInfo
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof PTYSessionInfo
     */
    createdAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof PTYSessionInfo
     */
    clients?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PTYSessionInfo
     */
    alive?: boolean;
}

/**
 * Check if a given object implements the PTYSessionInfo interface.
 */
export function instanceOfPTYSessionInfo(value: object): value is PTYSessionInfo {
    return true;
}

export function PTYSessionInfoFromJSON(json: any): PTYSessionInfo {
    return PTYSessionInfoFromJSONTyped(json, false);
}

export function PTYSessionInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PTYSessionInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'clients': json['clients'] == null ? undefined : json['clients'],
        'alive': json['alive'] == null ? undefined : json['alive'],
    };
}

export function PTYSessionInfoToJSON(json: any): PTYSessionInfo {
    return PTYSessionInfoToJSONTyped(json, false);
}

export function PTYSessionInfoToJSONTyped(value?: PTYSessionInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'clients': value['clients'],
        'alive': value['alive'],
    };
}

