/* tslint:disable */
/* eslint-disable */
/**
 * Hyper Fleet Native API
 * Hyper Fleet Native API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RegisterResponseData } from './RegisterResponseData';
import {
    RegisterResponseDataFromJSON,
    RegisterResponseDataFromJSONTyped,
    RegisterResponseDataToJSON,
    RegisterResponseDataToJSONTyped,
} from './RegisterResponseData';

/**
 * 
 * @export
 * @interface RegisterResponse
 */
export interface RegisterResponse {
    /**
     * 
     * @type {string}
     * @memberof RegisterResponse
     */
    message?: string;
    /**
     * 
     * @type {RegisterResponseData}
     * @memberof RegisterResponse
     */
    data?: RegisterResponseData;
}

/**
 * Check if a given object implements the RegisterResponse interface.
 */
export function instanceOfRegisterResponse(value: object): value is RegisterResponse {
    return true;
}

export function RegisterResponseFromJSON(json: any): RegisterResponse {
    return RegisterResponseFromJSONTyped(json, false);
}

export function RegisterResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : RegisterResponseDataFromJSON(json['data']),
    };
}

export function RegisterResponseToJSON(json: any): RegisterResponse {
    return RegisterResponseToJSONTyped(json, false);
}

export function RegisterResponseToJSONTyped(value?: RegisterResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'data': RegisterResponseDataToJSON(value['data']),
    };
}

