/* tslint:disable */
/* eslint-disable */
/**
 * Hyper Fleet Native API
 * Hyper Fleet Native API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterResponseData
 */
export interface RegisterResponseData {
    /**
     * 
     * @type {string}
     * @memberof RegisterResponseData
     */
    orgId?: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterResponseData
     */
    apiKey?: string;
}

/**
 * Check if a given object implements the RegisterResponseData interface.
 */
export function instanceOfRegisterResponseData(value: object): value is RegisterResponseData {
    return true;
}

export function RegisterResponseDataFromJSON(json: any): RegisterResponseData {
    return RegisterResponseDataFromJSONTyped(json, false);
}

export function RegisterResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'orgId': json['orgId'] == null ? undefined : json['orgId'],
        'apiKey': json['apiKey'] == null ? undefined : json['apiKey'],
    };
}

export function RegisterResponseDataToJSON(json: any): RegisterResponseData {
    return RegisterResponseDataToJSONTyped(json, false);
}

export function RegisterResponseDataToJSONTyped(value?: RegisterResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orgId': value['orgId'],
        'apiKey': value['apiKey'],
    };
}

