/* tslint:disable */
/* eslint-disable */
/**
 * Hyper Fleet Native API
 * Hyper Fleet Native API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResizeTerminalRequest
 */
export interface ResizeTerminalRequest {
    /**
     * 
     * @type {number}
     * @memberof ResizeTerminalRequest
     */
    cols: number;
    /**
     * 
     * @type {number}
     * @memberof ResizeTerminalRequest
     */
    rows: number;
}

/**
 * Check if a given object implements the ResizeTerminalRequest interface.
 */
export function instanceOfResizeTerminalRequest(value: object): value is ResizeTerminalRequest {
    if (!('cols' in value) || value['cols'] === undefined) return false;
    if (!('rows' in value) || value['rows'] === undefined) return false;
    return true;
}

export function ResizeTerminalRequestFromJSON(json: any): ResizeTerminalRequest {
    return ResizeTerminalRequestFromJSONTyped(json, false);
}

export function ResizeTerminalRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResizeTerminalRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'cols': json['cols'],
        'rows': json['rows'],
    };
}

export function ResizeTerminalRequestToJSON(json: any): ResizeTerminalRequest {
    return ResizeTerminalRequestToJSONTyped(json, false);
}

export function ResizeTerminalRequestToJSONTyped(value?: ResizeTerminalRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cols': value['cols'],
        'rows': value['rows'],
    };
}

