/* tslint:disable */
/* eslint-disable */
/**
 * VoidRun API
 * VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RestoreSandboxRequest
 */
export interface RestoreSandboxRequest {
    /**
     * 
     * @type {string}
     * @memberof RestoreSandboxRequest
     */
    newId: string;
    /**
     * 
     * @type {string}
     * @memberof RestoreSandboxRequest
     */
    snapshotPath: string;
    /**
     * 
     * @type {string}
     * @memberof RestoreSandboxRequest
     */
    newIp?: string;
    /**
     * Start in stopped state
     * @type {boolean}
     * @memberof RestoreSandboxRequest
     */
    cold?: boolean;
    /**
     * 
     * @type {number}
     * @memberof RestoreSandboxRequest
     */
    cpu?: number;
    /**
     * 
     * @type {number}
     * @memberof RestoreSandboxRequest
     */
    mem?: number;
    /**
     * 
     * @type {string}
     * @memberof RestoreSandboxRequest
     */
    orgId: string;
    /**
     * 
     * @type {string}
     * @memberof RestoreSandboxRequest
     */
    userId?: string;
}

/**
 * Check if a given object implements the RestoreSandboxRequest interface.
 */
export function instanceOfRestoreSandboxRequest(value: object): value is RestoreSandboxRequest {
    if (!('newId' in value) || value['newId'] === undefined) return false;
    if (!('snapshotPath' in value) || value['snapshotPath'] === undefined) return false;
    if (!('orgId' in value) || value['orgId'] === undefined) return false;
    return true;
}

export function RestoreSandboxRequestFromJSON(json: any): RestoreSandboxRequest {
    return RestoreSandboxRequestFromJSONTyped(json, false);
}

export function RestoreSandboxRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestoreSandboxRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'newId': json['new_id'],
        'snapshotPath': json['snapshot_path'],
        'newIp': json['new_ip'] == null ? undefined : json['new_ip'],
        'cold': json['cold'] == null ? undefined : json['cold'],
        'cpu': json['cpu'] == null ? undefined : json['cpu'],
        'mem': json['mem'] == null ? undefined : json['mem'],
        'orgId': json['orgId'],
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function RestoreSandboxRequestToJSON(json: any): RestoreSandboxRequest {
    return RestoreSandboxRequestToJSONTyped(json, false);
}

export function RestoreSandboxRequestToJSONTyped(value?: RestoreSandboxRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'new_id': value['newId'],
        'snapshot_path': value['snapshotPath'],
        'new_ip': value['newIp'],
        'cold': value['cold'],
        'cpu': value['cpu'],
        'mem': value['mem'],
        'orgId': value['orgId'],
        'userId': value['userId'],
    };
}

