/* tslint:disable */
/* eslint-disable */
/**
 * Hyper Fleet Native API
 * Hyper Fleet Native API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RunBackgroundCommandRequest
 */
export interface RunBackgroundCommandRequest {
    /**
     * 
     * @type {string}
     * @memberof RunBackgroundCommandRequest
     */
    command: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof RunBackgroundCommandRequest
     */
    env?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof RunBackgroundCommandRequest
     */
    cwd?: string;
    /**
     * Command timeout in seconds (0 = no timeout, max 900)
     * @type {number}
     * @memberof RunBackgroundCommandRequest
     */
    timeout?: number;
}

/**
 * Check if a given object implements the RunBackgroundCommandRequest interface.
 */
export function instanceOfRunBackgroundCommandRequest(value: object): value is RunBackgroundCommandRequest {
    if (!('command' in value) || value['command'] === undefined) return false;
    return true;
}

export function RunBackgroundCommandRequestFromJSON(json: any): RunBackgroundCommandRequest {
    return RunBackgroundCommandRequestFromJSONTyped(json, false);
}

export function RunBackgroundCommandRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunBackgroundCommandRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'command': json['command'],
        'env': json['env'] == null ? undefined : json['env'],
        'cwd': json['cwd'] == null ? undefined : json['cwd'],
        'timeout': json['timeout'] == null ? undefined : json['timeout'],
    };
}

export function RunBackgroundCommandRequestToJSON(json: any): RunBackgroundCommandRequest {
    return RunBackgroundCommandRequestToJSONTyped(json, false);
}

export function RunBackgroundCommandRequestToJSONTyped(value?: RunBackgroundCommandRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'command': value['command'],
        'env': value['env'],
        'cwd': value['cwd'],
        'timeout': value['timeout'],
    };
}

