/* tslint:disable */
/* eslint-disable */
/**
 * VoidRun API
 * VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Sandbox
 */
export interface Sandbox {
    /**
     * 
     * @type {string}
     * @memberof Sandbox
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Sandbox
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Sandbox
     */
    imageId?: string;
    /**
     * 
     * @type {string}
     * @memberof Sandbox
     */
    ip?: string;
    /**
     * 
     * @type {number}
     * @memberof Sandbox
     */
    cpu?: number;
    /**
     * 
     * @type {number}
     * @memberof Sandbox
     */
    mem?: number;
    /**
     * 
     * @type {string}
     * @memberof Sandbox
     */
    status?: SandboxStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof Sandbox
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Sandbox
     */
    createdBy?: string;
    /**
     * 
     * @type {string}
     * @memberof Sandbox
     */
    orgId?: string;
    /**
     * Environment variables set on the sandbox
     * @type {{ [key: string]: string; }}
     * @memberof Sandbox
     */
    envVars?: { [key: string]: string; };
}


/**
 * @export
 */
export const SandboxStatusEnum = {
    Running: 'running',
    Stopped: 'stopped',
    Paused: 'paused',
    Error: 'error'
} as const;
export type SandboxStatusEnum = typeof SandboxStatusEnum[keyof typeof SandboxStatusEnum];


/**
 * Check if a given object implements the Sandbox interface.
 */
export function instanceOfSandbox(value: object): value is Sandbox {
    return true;
}

export function SandboxFromJSON(json: any): Sandbox {
    return SandboxFromJSONTyped(json, false);
}

export function SandboxFromJSONTyped(json: any, ignoreDiscriminator: boolean): Sandbox {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'imageId': json['imageId'] == null ? undefined : json['imageId'],
        'ip': json['ip'] == null ? undefined : json['ip'],
        'cpu': json['cpu'] == null ? undefined : json['cpu'],
        'mem': json['mem'] == null ? undefined : json['mem'],
        'status': json['status'] == null ? undefined : json['status'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'orgId': json['orgId'] == null ? undefined : json['orgId'],
        'envVars': json['envVars'] == null ? undefined : json['envVars'],
    };
}

export function SandboxToJSON(json: any): Sandbox {
    return SandboxToJSONTyped(json, false);
}

export function SandboxToJSONTyped(value?: Sandbox | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'imageId': value['imageId'],
        'ip': value['ip'],
        'cpu': value['cpu'],
        'mem': value['mem'],
        'status': value['status'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'createdBy': value['createdBy'],
        'orgId': value['orgId'],
        'envVars': value['envVars'],
    };
}

