/* tslint:disable */
/* eslint-disable */
/**
 * VoidRun API
 * VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/version` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Sandbox
 */
export interface Sandbox {
    /**
     * 
     * @type {string}
     * @memberof Sandbox
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Sandbox
     */
    name?: string;
    /**
     * Image name or ID used to create the sandbox
     * @type {string}
     * @memberof Sandbox
     */
    image?: string;
    /**
     * Number of vCPUs allocated
     * @type {number}
     * @memberof Sandbox
     */
    cpu?: number;
    /**
     * Memory in MiB
     * @type {number}
     * @memberof Sandbox
     */
    mem?: number;
    /**
     * Disk size in MiB
     * @type {number}
     * @memberof Sandbox
     */
    diskMB?: number;
    /**
     * 
     * @type {string}
     * @memberof Sandbox
     */
    status?: SandboxStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof Sandbox
     */
    createdAt?: Date;
    /**
     * User ID who created the sandbox
     * @type {string}
     * @memberof Sandbox
     */
    createdBy?: string;
    /**
     * Organization ID the sandbox belongs to
     * @type {string}
     * @memberof Sandbox
     */
    orgId?: string;
    /**
     * Environment variables set on the sandbox (optional, only present if configured)
     * @type {{ [key: string]: string; }}
     * @memberof Sandbox
     */
    envVars?: { [key: string]: string; };
    /**
     * Indicates if auto-pause is disabled
     * @type {boolean}
     * @memberof Sandbox
     */
    disablePause?: boolean;
    /**
     * Region where the sandbox is hosted
     * @type {string}
     * @memberof Sandbox
     */
    region?: string;
    /**
     * External reference ID
     * @type {string}
     * @memberof Sandbox
     */
    refId?: string;
}


/**
 * @export
 */
export const SandboxStatusEnum = {
    Running: 'running',
    Stopped: 'stopped',
    Paused: 'paused',
    Error: 'error'
} as const;
export type SandboxStatusEnum = typeof SandboxStatusEnum[keyof typeof SandboxStatusEnum];


/**
 * Check if a given object implements the Sandbox interface.
 */
export function instanceOfSandbox(value: object): value is Sandbox {
    return true;
}

export function SandboxFromJSON(json: any): Sandbox {
    return SandboxFromJSONTyped(json, false);
}

export function SandboxFromJSONTyped(json: any, ignoreDiscriminator: boolean): Sandbox {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'image': json['image'] == null ? undefined : json['image'],
        'cpu': json['cpu'] == null ? undefined : json['cpu'],
        'mem': json['mem'] == null ? undefined : json['mem'],
        'diskMB': json['diskMB'] == null ? undefined : json['diskMB'],
        'status': json['status'] == null ? undefined : json['status'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'orgId': json['orgId'] == null ? undefined : json['orgId'],
        'envVars': json['envVars'] == null ? undefined : json['envVars'],
        'disablePause': json['disablePause'] == null ? undefined : json['disablePause'],
        'region': json['region'] == null ? undefined : json['region'],
        'refId': json['refId'] == null ? undefined : json['refId'],
    };
}

export function SandboxToJSON(json: any): Sandbox {
    return SandboxToJSONTyped(json, false);
}

export function SandboxToJSONTyped(value?: Sandbox | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'image': value['image'],
        'cpu': value['cpu'],
        'mem': value['mem'],
        'diskMB': value['diskMB'],
        'status': value['status'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'createdBy': value['createdBy'],
        'orgId': value['orgId'],
        'envVars': value['envVars'],
        'disablePause': value['disablePause'],
        'region': value['region'],
        'refId': value['refId'],
    };
}

