/* tslint:disable */
/* eslint-disable */
/**
 * VoidRun API
 * VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` and `/api/version` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SessionExecStreamRequest
 */
export interface SessionExecStreamRequest {
    /**
     * 
     * @type {string}
     * @memberof SessionExecStreamRequest
     */
    sessionId: string;
    /**
     * 
     * @type {string}
     * @memberof SessionExecStreamRequest
     */
    command: string;
}

/**
 * Check if a given object implements the SessionExecStreamRequest interface.
 */
export function instanceOfSessionExecStreamRequest(value: object): value is SessionExecStreamRequest {
    if (!('sessionId' in value) || value['sessionId'] === undefined) return false;
    if (!('command' in value) || value['command'] === undefined) return false;
    return true;
}

export function SessionExecStreamRequestFromJSON(json: any): SessionExecStreamRequest {
    return SessionExecStreamRequestFromJSONTyped(json, false);
}

export function SessionExecStreamRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionExecStreamRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'sessionId': json['sessionId'],
        'command': json['command'],
    };
}

export function SessionExecStreamRequestToJSON(json: any): SessionExecStreamRequest {
    return SessionExecStreamRequestToJSONTyped(json, false);
}

export function SessionExecStreamRequestToJSONTyped(value?: SessionExecStreamRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sessionId': value['sessionId'],
        'command': value['command'],
    };
}

