/* tslint:disable */
/* eslint-disable */
/**
 * VoidRun API
 * VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` and `/api/version` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SessionExecResponse
 */
export interface SessionExecResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SessionExecResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SessionExecResponse
     */
    sessionId?: string;
    /**
     * 
     * @type {string}
     * @memberof SessionExecResponse
     */
    output?: string;
    /**
     * 
     * @type {string}
     * @memberof SessionExecResponse
     */
    error?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SessionExecResponse
     */
    exitCode?: number;
}

/**
 * Check if a given object implements the SessionExecResponse interface.
 */
export function instanceOfSessionExecResponse(value: object): value is SessionExecResponse {
    return true;
}

export function SessionExecResponseFromJSON(json: any): SessionExecResponse {
    return SessionExecResponseFromJSONTyped(json, false);
}

export function SessionExecResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionExecResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'sessionId': json['sessionId'] == null ? undefined : json['sessionId'],
        'output': json['output'] == null ? undefined : json['output'],
        'error': json['error'] == null ? undefined : json['error'],
        'exitCode': json['exitCode'] == null ? undefined : json['exitCode'],
    };
}

export function SessionExecResponseToJSON(json: any): SessionExecResponse {
    return SessionExecResponseToJSONTyped(json, false);
}

export function SessionExecResponseToJSONTyped(value?: SessionExecResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'sessionId': value['sessionId'],
        'output': value['output'],
        'error': value['error'],
        'exitCode': value['exitCode'],
    };
}

