/* tslint:disable */
/* eslint-disable */
/**
 * VoidRun API
 * VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/version` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SessionExecRequest
 */
export interface SessionExecRequest {
    /**
     * 
     * @type {string}
     * @memberof SessionExecRequest
     */
    action: SessionExecRequestActionEnum;
    /**
     * Required for all actions except create
     * @type {string}
     * @memberof SessionExecRequest
     */
    sessionId?: string;
    /**
     * 
     * @type {string}
     * @memberof SessionExecRequest
     */
    shell?: string;
    /**
     * Required when action is `exec`
     * @type {string}
     * @memberof SessionExecRequest
     */
    command?: string;
    /**
     * Input text when action is `input`
     * @type {string}
     * @memberof SessionExecRequest
     */
    input?: string;
    /**
     * Required when action is `resize`
     * @type {number}
     * @memberof SessionExecRequest
     */
    cols?: number;
    /**
     * Required when action is `resize`
     * @type {number}
     * @memberof SessionExecRequest
     */
    rows?: number;
}


/**
 * @export
 */
export const SessionExecRequestActionEnum = {
    Create: 'create',
    Exec: 'exec',
    Input: 'input',
    Resize: 'resize',
    Close: 'close'
} as const;
export type SessionExecRequestActionEnum = typeof SessionExecRequestActionEnum[keyof typeof SessionExecRequestActionEnum];


/**
 * Check if a given object implements the SessionExecRequest interface.
 */
export function instanceOfSessionExecRequest(value: object): value is SessionExecRequest {
    if (!('action' in value) || value['action'] === undefined) return false;
    return true;
}

export function SessionExecRequestFromJSON(json: any): SessionExecRequest {
    return SessionExecRequestFromJSONTyped(json, false);
}

export function SessionExecRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionExecRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'action': json['action'],
        'sessionId': json['sessionId'] == null ? undefined : json['sessionId'],
        'shell': json['shell'] == null ? undefined : json['shell'],
        'command': json['command'] == null ? undefined : json['command'],
        'input': json['input'] == null ? undefined : json['input'],
        'cols': json['cols'] == null ? undefined : json['cols'],
        'rows': json['rows'] == null ? undefined : json['rows'],
    };
}

export function SessionExecRequestToJSON(json: any): SessionExecRequest {
    return SessionExecRequestToJSONTyped(json, false);
}

export function SessionExecRequestToJSONTyped(value?: SessionExecRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': value['action'],
        'sessionId': value['sessionId'],
        'shell': value['shell'],
        'command': value['command'],
        'input': value['input'],
        'cols': value['cols'],
        'rows': value['rows'],
    };
}

