/* tslint:disable */
/* eslint-disable */
/**
 * Hyper Fleet Native API
 * Hyper Fleet Native API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StartWatch200ResponseData } from './StartWatch200ResponseData';
import {
    StartWatch200ResponseDataFromJSON,
    StartWatch200ResponseDataFromJSONTyped,
    StartWatch200ResponseDataToJSON,
    StartWatch200ResponseDataToJSONTyped,
} from './StartWatch200ResponseData';

/**
 * 
 * @export
 * @interface StartWatch200Response
 */
export interface StartWatch200Response {
    /**
     * 
     * @type {string}
     * @memberof StartWatch200Response
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof StartWatch200Response
     */
    message?: string;
    /**
     * 
     * @type {StartWatch200ResponseData}
     * @memberof StartWatch200Response
     */
    data?: StartWatch200ResponseData;
}

/**
 * Check if a given object implements the StartWatch200Response interface.
 */
export function instanceOfStartWatch200Response(value: object): value is StartWatch200Response {
    return true;
}

export function StartWatch200ResponseFromJSON(json: any): StartWatch200Response {
    return StartWatch200ResponseFromJSONTyped(json, false);
}

export function StartWatch200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartWatch200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : StartWatch200ResponseDataFromJSON(json['data']),
    };
}

export function StartWatch200ResponseToJSON(json: any): StartWatch200Response {
    return StartWatch200ResponseToJSONTyped(json, false);
}

export function StartWatch200ResponseToJSONTyped(value?: StartWatch200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'message': value['message'],
        'data': StartWatch200ResponseDataToJSON(value['data']),
    };
}

