/* tslint:disable */
/* eslint-disable */
/**
 * VoidRun API
 * VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StartWatch200ResponseData
 */
export interface StartWatch200ResponseData {
    /**
     * 
     * @type {string}
     * @memberof StartWatch200ResponseData
     */
    sessionId?: string;
}

/**
 * Check if a given object implements the StartWatch200ResponseData interface.
 */
export function instanceOfStartWatch200ResponseData(value: object): value is StartWatch200ResponseData {
    return true;
}

export function StartWatch200ResponseDataFromJSON(json: any): StartWatch200ResponseData {
    return StartWatch200ResponseDataFromJSONTyped(json, false);
}

export function StartWatch200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartWatch200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'sessionId': json['sessionId'] == null ? undefined : json['sessionId'],
    };
}

export function StartWatch200ResponseDataToJSON(json: any): StartWatch200ResponseData {
    return StartWatch200ResponseDataToJSONTyped(json, false);
}

export function StartWatch200ResponseDataToJSONTyped(value?: StartWatch200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sessionId': value['sessionId'],
    };
}

