/* tslint:disable */
/* eslint-disable */
/**
 * Hyper Fleet Native API
 * Hyper Fleet Native API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StartWatchRequest
 */
export interface StartWatchRequest {
    /**
     * 
     * @type {string}
     * @memberof StartWatchRequest
     */
    path: string;
    /**
     * 
     * @type {boolean}
     * @memberof StartWatchRequest
     */
    recursive?: boolean;
    /**
     * Skip directories that start with '.'
     * @type {boolean}
     * @memberof StartWatchRequest
     */
    ignoreHidden?: boolean;
}

/**
 * Check if a given object implements the StartWatchRequest interface.
 */
export function instanceOfStartWatchRequest(value: object): value is StartWatchRequest {
    if (!('path' in value) || value['path'] === undefined) return false;
    return true;
}

export function StartWatchRequestFromJSON(json: any): StartWatchRequest {
    return StartWatchRequestFromJSONTyped(json, false);
}

export function StartWatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartWatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'path': json['path'],
        'recursive': json['recursive'] == null ? undefined : json['recursive'],
        'ignoreHidden': json['ignoreHidden'] == null ? undefined : json['ignoreHidden'],
    };
}

export function StartWatchRequestToJSON(json: any): StartWatchRequest {
    return StartWatchRequestToJSONTyped(json, false);
}

export function StartWatchRequestToJSONTyped(value?: StartWatchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'path': value['path'],
        'recursive': value['recursive'],
        'ignoreHidden': value['ignoreHidden'],
    };
}

