/* tslint:disable */
/* eslint-disable */
/**
 * VoidRun API
 * VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/version` require the `X-API-Key` header for authentication. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface UpdateSandboxRequest
 */
export interface UpdateSandboxRequest {
    /**
     * If true, auto-snapshot after idle. If false, skip idle snapshot. Takes effect on the next lifecycle scan. Does not cancel auto-delete of an already-snapshotted sandbox.
     * @type {boolean}
     * @memberof UpdateSandboxRequest
     */
    autoSleep?: boolean;
}

/**
 * Check if a given object implements the UpdateSandboxRequest interface.
 */
export function instanceOfUpdateSandboxRequest(value: object): value is UpdateSandboxRequest {
    return true;
}

export function UpdateSandboxRequestFromJSON(json: any): UpdateSandboxRequest {
    return UpdateSandboxRequestFromJSONTyped(json, false);
}

export function UpdateSandboxRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSandboxRequest {
    if (json == null) {
        return json;
    }
    return {
        'autoSleep': json['autoSleep'] == null ? undefined : json['autoSleep'],
    };
}

export function UpdateSandboxRequestToJSON(json: any): UpdateSandboxRequest {
    return UpdateSandboxRequestToJSONTyped(json, false);
}

export function UpdateSandboxRequestToJSONTyped(value?: UpdateSandboxRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        'autoSleep': value['autoSleep'],
    };
}
